### PR TITLE
PlacementStruct1

### PR DESCRIPTION
**Pull request by ThePixelGamer**
~~Requies open-ead/sead#96~~
Should be squashed before merging

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)* status: all files reviewed, 9 unresolved discussions (waiting on @ThePixelGamer)

___
*[src/KingSystem/Map/mapLazyTraverseList.h, line 18 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDvNND2gh-Aue5UFWN:-MvDvNND2gh-Aue5UFWO:b3mbsga) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapLazyTraverseList.h#L18)):*
> ```objc
>     bool wereFlagsUpdated();
> 
>     bool empty() { return !mHasEntries; }
> ```

`bool empty() const`
___
*[src/KingSystem/Map/mapPlacementActors.h, line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDvSEmB2lEkQ7MLHnh:-MvDvSEmB2lEkQ7MLHni:b-8adbgc) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementActors.h#L9)):*
> ```objc
> #include <thread/seadAtomic.h>
> #include <thread/seadReadWriteLock.h>
> #include "KingSystem/Map/mapPlacementAreaMgr.h"
> ```

This can probably be replaced with a forward declaration. We want to avoid unnecessary includes as much as possible to reduce compile times.
___
*[src/KingSystem/Map/mapPlacementAreaMgr.h, line 29 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDvof03r9NfmmyynX5:-MvDvof03r9NfmmyynX6:b-luotox) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.h#L29)):*
> ```objc
>     public:
>         Axis() = default;
>         Axis(const sead::Vector3f& v) : Axis(v, v) {}
> ```

`explicit Axis(...)`
___
*[src/KingSystem/Map/mapPlacementAreaMgr.h, line 173 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDw5y49B0fs9X_cQxs:-MvDw5y49B0fs9X_cQxt:b-8ug64q) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.h#L173)):*
> ```objc
>     ~PlacementAreaMgr();
> 
>     bool parseAreas(const sead::SafeString& unitConfigName, const MubinIter& objIter);  // d1cecc
> ```

Could you put each comment above the line it's describing? Otherwise any line width change to e.g. `parseAreas` will cause all the other lines to change as clang-format tries to keep the comments aligned -- which makes diffs super noisy.

(also the comments are mostly only useful for functions that haven't been implemented yet -- I would remove them from functions that *are* implemented)
___
*[src/KingSystem/Map/mapPlacementAreaMgr.h, line 181 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDx8-t7t15kPTFMljK:-MvDx8-t7t15kPTFMljL:bngarql) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.h#L181)):*
> ```objc
>     bool insideInnerHideCalc(const int& idx);                                           // d1f900
>     bool insideInnerHideLoad(const int& idx);                                           // d1facc
>     void loadDemoCulling(const sead::SafeString& demoName);                             // d1fc98
> ```

`demo_name` (snake_case for variables that aren't class members)
___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 52 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDxfLh5p45jpqU_XjO:-MvDxfLh5p45jpqU_XjP:byq7fx6) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L52)):*
> ```cpp
> }
> 
> // NON_MATCHING: I'm just bad but should be a template to try and fix
> ```

Could you give a high level overview of what doesn't match? (otherwise the comment isn't super useful)
___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 436 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDy1km0GQLkJqT3PHT:-MvDy1km0GQLkJqT3PHU:btpu49) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L436)):*
> ```cpp
> 
> // too specific for sead
> float sqXZDistance(const sead::Vector3f& a, const sead::Vector3f& b) {
> ```

this should be marked `static`
___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 446 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDyC9j47rRAhX7o2C-:-MvDyC9j47rRAhX7o2C0:b6ye4rm) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L446)):*
> ```cpp
>         }
> 
>         if (mActiveNpc != 6) {
> ```

Consider inverting this condition and the first if statement in this function: `if (mActiveNpc == 6) return sqXZDistance(...);` is more natural and reduces indentation in the rest of the function.
___
*[src/KingSystem/Map/mapStagePreActorCache.h, line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/81#-MvDydqK5zyhrotyJG-s:-MvDydqK5zyhrotyJG-t:bc60d97) ([raw file](https://github.com/zeldaret/botw/blob/ca297f16c8e0e1b584ccea8967d23932ffdf9d15/src/KingSystem/Map/mapStagePreActorCache.h#L20)):*
> ```objc
> 
> public:
>     LazyTraverseList* getObjects() { return mObjects; }
> ```

can be const

**Review by leoetlino — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)* status: all files reviewed, 4 unresolved discussions (waiting on @ThePixelGamer)

___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 437 at r2](https://reviewable.io/reviews/zeldaret/botw/81#-MvEVSYC0vASdbOpZNz9:-MvEVSYC0vASdbOpZNzA:b3i47hp) ([raw file](https://github.com/zeldaret/botw/blob/231be5cc536f821ce002137ce3b3c82fa56797e0/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L437)):*
> ```cpp
> 
> bool PlacementAreaMgr::insideInnerHideTrans(const int& idx) {
>     if (mActiveNpc != mInnerHide[idx]._12c)
> ```

the if body spans two lines so it should be braced
___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 444 at r2](https://reviewable.io/reviews/zeldaret/botw/81#-MvEVeD47Qa8okAaGZx9:-MvEVeD47Qa8okAaGZxA:b-skfgnv) ([raw file](https://github.com/zeldaret/botw/blob/231be5cc536f821ce002137ce3b3c82fa56797e0/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L444)):*
> ```cpp
>         return true;
> 
>     if (mActiveNpc == 6)
> ```

braces
___
*[lib/sead, line 1 at r2](https://reviewable.io/reviews/zeldaret/botw/81#-MvEVmCYApgPzNdkzAb4:-MvEVmCYApgPzNdkzAb5:b-6czftt) ([raw file](https://github.com/zeldaret/botw/blob/231be5cc536f821ce002137ce3b3c82fa56797e0/lib/sead#L1)):*
> ```
> Subproject commit 3dd89df7658f15716a1fe560898a5dad0bfb63c2
> ```

Did you accidentally update the module?

**Review by leoetlino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)* status: all files reviewed, 3 unresolved discussions (waiting on @ThePixelGamer)

___
*[lib/sead, line 1 at r2](https://reviewable.io/reviews/zeldaret/botw/81#-MvEVmCYApgPzNdkzAb4:-MvEWouB4vUmTi-KjUCj:b3j0hmd) ([raw file](https://github.com/zeldaret/botw/blob/231be5cc536f821ce002137ce3b3c82fa56797e0/lib/sead#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Did you accidentally update the module?
</blockquote></details>

Never mind, you just reverted the submodule update

**Review by ThePixelGamer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @leoetlino and @ThePixelGamer)

___
*[src/KingSystem/Map/mapPlacementAreaMgr.cpp, line 437 at r2](https://reviewable.io/reviews/zeldaret/botw/81#-MvEVSYC0vASdbOpZNz9:-MvEjOIP0sF75_meuF92:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/231be5cc536f821ce002137ce3b3c82fa56797e0/src/KingSystem/Map/mapPlacementAreaMgr.cpp#L437)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the if body spans two lines so it should be braced
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Review by leoetlino — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/81#-:-MvGMABY9wQyyC2hzOFS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Pull request merged**
