### PR TITLE
CSV formatting improvements

### PR DESCRIPTION
**Pull request by AlexApps99**
I am not 100% sure that everything has been converted correctly, nor that the scripts have all been modified to reflect these changes.

The script used for conversion is as follows:
```python3
import csv

prefixes = ("sub_")
good_prefixes = ("eco::", "ui::")

last_addr = 0
with open("data/ukf.csv", "r") as csvfile, open("data/uking_functions.csv", "w") as f:
    w = csv.writer(f)
    w.writerow(["Address", "Quality", "Size", "Name"])
    for row in csv.reader(csvfile):
        addr = row[0].strip()
        ida_name = row[1].strip()
        if not ida_name.startswith(good_prefixes) and "sub" in ida_name.lower() and "nullsub" not in ida_name.lower() and ida_name.lower().endswith(addr[-10:].lower()):
            if not ida_name.lower().startswith("sub"):
                print(ida_name)
                assert False
            ida_name = ""
        name = ida_name
        size = "{:06d}".format(int(row[2].strip(), 0))
        assert len(size) == 6
        code_name = row[3].strip()
        quality = "U"
        #if "nullsub" in name:
        #    print(name, size)

        addr_val = int(row[0], 16)
        assert addr_val > last_addr
        last_addr = addr_val
        addr = "0x{0:016x}".format(addr_val)
        assert len(addr) == 18

        assert not ida_name or (ida_name[-1] != "?" and ida_name[-1] != "!")

        assert int(size) > 1

        if code_name and code_name != "l":
            assert len(code_name) > 1
            if code_name[-1] == "?":
                quality = "m"
                name = code_name[:-1]
            elif code_name[-1] == "!":
                quality = "M"
                name = code_name[:-1]
            else:
                quality = "O"
                name = code_name
        elif code_name == "l":
            quality = "L"

        if set(name) == {"x"}:
            print(row)
            name = ""

        #assert name
        w.writerow([addr, quality, size, name])
```

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/50)

### CODE REVIEW

**Comment by AlexApps99** [comment]
Ah, I forgot to skip the headers, will amend this now

**Review by leoetlino — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexApps99)

**Comment by AlexApps99** [comment]
An example of the new format follows:
```csv
Address,Quality,Size,Name
...
0x00000071002df93c,O,000128,_ZN5uking3act18WeaponModifierInfo30pickRandomYellowModifierAmiiboERKN4sead14SafeStringBaseIcEE
0x00000071002df9bc,M,000480,_ZN5uking3act18WeaponModifierInfo26pickRandomBlueModifierTboxERKN4sead14SafeStringBaseIcEE
0x00000071002dfb9c,O,000628,_ZN5uking3act18WeaponModifierInfo18pickRandomModifierERKNS0_20WeaponModifierRangesE
0x00000071002dfe10,m,000292,_ZN5uking3act18WeaponModifierInfo27pickRandomBlueModifierActorERKN4ksys3act20ActorConstDataAccessE
0x00000071002dff34,M,000480,_ZN5uking3act18WeaponModifierInfo28pickRandomYellowModifierTboxERKN4sead14SafeStringBaseIcEE
0x00000071002e0114,M,000516,_ZN5uking3act18WeaponModifierInfo29pickRandomYellowModifierActorERKN4ksys3act20ActorConstDataAccessE
0x00000071002e0318,U,000404,weaponBonusStuff_0
0x00000071002e04ac,U,000876,Weapon::ctor
0x00000071002e0818,U,000108,Weapon::invokedEmitBlinkEffect
0x00000071002e0884,U,001376,Weapon::init1
0x00000071002e0de4,U,000836,Weapon::x
0x00000071002e1128,U,000004,j_nullsub_4074
0x00000071002e112c,U,000316,Weapon::m20
0x00000071002e1268,U,000468,Weapon::init2
0x00000071002e143c,U,000780,Weapon::m63
0x00000071002e1748,U,000132,
0x00000071002e17cc,U,000408,
...
```
Possible quality values:
- `O`: OK
- `m`: Minor difference
- `M`: Major difference
- `W`: WIP
- `U`: Undecompiled
- `L`: Library

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexApps99)

**Pull request merged**
