### PR TITLE
Decompile some Action classes

### PR DESCRIPTION
**Pull request by notyourav**
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/104)

### CODE REVIEW

**Comment by leoetlino** [comment]
Since we now know that isFork() isn't really a more accurate name for isFlag4Set(), I think we should probably revert the isFork() changes? Or should we find a better name for it?

**Comment by leoetlino** [comment]
(also, it'd be great if you could split large independent diffs such as the isFork changes and put them in a separate commit or PR in the future -- makes the PR easier to review)

**Review by leoetlino — COMMENTED** [review]
Mostly LGTM, just several minor things

Also, could you update data/status_action.yml please? Thanks!

> Reviewed 51 of 51 files at r1, 3 of 3 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/104#-:-NEc7UCpEV2tV1NS7KEc:b-dwwn9g)* status: all files reviewed, 8 unresolved discussions (waiting on @notyourav)

___
*[`src/Game/AI/Action/actionEventHoverNullASPlay.cpp` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7mvcCbcYFqh9q5zN:-NEc7mvcCbcYFqh9q5zO:btuncyz) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/Game/AI/Action/actionEventHoverNullASPlay.cpp#L21)):*
> ```cpp
> 
> void EventHoverNullASPlay::leave_() {
>     [&](ksys::act::Actor* actor) {
> ```

Does this match as a separate member function (either on EventHoverNullASPlay, or on CCAccessor)? This looks kinda sus
___
*[`src/Game/AI/Action/actionNPCStartTurnToPlayer.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc8SKF4Hsfig_-oCjN:-NEc8SKF4Hsfig_-oCjO:b-h83jtp) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/Game/AI/Action/actionNPCStartTurnToPlayer.cpp#L16)):*
> ```cpp
> 
> bool NPCStartTurnToPlayer::oneShot_() {
>     mValue = *mTurnRange_d * 0.5;
> ```

0.5f to appease clang-tidy's double->float implicit conversion warning
___
*[`src/KingSystem/ActorSystem/actActor.h` line 145 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc6bdPEWGRDqfPKV2z:-NEc6bdPEWGRDqfPKV3-:b-fxzcd3) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/actActor.h#L145)):*
> ```objc
>     const sead::Vector3f& getAngVelocity() const { return mAngVelocity; }
>     const sead::Vector3f& getScale() const { return mScale; }
>     phys::RigidBody* getMainBody() { return mMainBody; }
> ```

This can be const-qualified (`phys::RigidBody* getMainBody() const { ... }`)
___
*[`src/KingSystem/ActorSystem/actActor.h` line 146 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc6e3bAYMOej_gC_Au:-NEc6e3bAYMOej_gC_Av:b-7ropln) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/actActor.h#L146)):*
> ```objc
>     const sead::Vector3f& getScale() const { return mScale; }
>     phys::RigidBody* getMainBody() { return mMainBody; }
>     phys::RigidBody* getTgtBody() { return mTgtBody; }
> ```

ditto
___
*[`src/KingSystem/ActorSystem/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc78V03hD3Unq_yrWu:-NEc78V03hD3Unq_yrWv:b9oek8p) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/CMakeLists.txt#L2)):*
> ```CMake
> target_sources(uking PRIVATE
>         Attention/actAttention.cpp
> ```

Could you revert the indentation changes?
___
*[`src/KingSystem/Physics/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7Ebr7L-YzKxMgtoo:-NEc7Ebr7L-YzKxMgtop:b-pb9bm7) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/Physics/CMakeLists.txt#L2)):*
> ```CMake
> target_sources(uking PRIVATE
>         CharacterController/physCharacterController.h
> ```

indent
___
*[`src/KingSystem/Physics/System/physInstanceSet.h` line 77 at r2](https://reviewable.io/reviews/zeldaret/botw/104#-NEc8lbY0fyAotYzy-a1:-NEc8lbY0fyAotYzy-a2:b-mqurkt) ([raw file](https://github.com/zeldaret/botw/blob/3048531650109843d66d01eadcac4ef9e4181aae/src/KingSystem/Physics/System/physInstanceSet.h#L77)):*
> ```objc
>     void sub_7100FBB4B4();
>     void* findX(const sead::SafeString& a1, const sead::SafeString& a2) const;
>     void* findRigidBody(const sead::SafeString& name) const;
> ```

Can we change this to return a `RigidBody*`?
___
*[`src/KingSystem/System/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7LiF4_p8G57gr4bw:-NEc7LiF4_p8G57gr4bx:b-pb9bm7) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/System/CMakeLists.txt#L2)):*
> ```CMake
> target_sources(uking PRIVATE
>         Account.cpp
> ```

indent

**Review by notyourav — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/104#-:-NEcUYwG4rN_Oh1S0G7W:bnfp4nl)* status: 21 of 52 files reviewed, 8 unresolved discussions (waiting on @leoetlino)

___
*[`src/Game/AI/Action/actionEventHoverNullASPlay.cpp` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7mvcCbcYFqh9q5zN:-NEcTuU-7SHsI2QPc9UN:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/Game/AI/Action/actionEventHoverNullASPlay.cpp#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match as a separate member function (either on EventHoverNullASPlay, or on CCAccessor)? This looks kinda sus
</blockquote></details>

Done.
___
*[`src/Game/AI/Action/actionNPCStartTurnToPlayer.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc8SKF4Hsfig_-oCjN:-NEcU-St0SyqjwqE9FkU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/Game/AI/Action/actionNPCStartTurnToPlayer.cpp#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

0.5f to appease clang-tidy's double->float implicit conversion warning
</blockquote></details>

Done.
___
*[`src/KingSystem/ActorSystem/actActor.h` line 145 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc6bdPEWGRDqfPKV2z:-NEcUVj53OOsRnK4miWu:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/actActor.h#L145)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This can be const-qualified (`phys::RigidBody* getMainBody() const { ... }`)
</blockquote></details>

Done.
___
*[`src/KingSystem/ActorSystem/actActor.h` line 146 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc6e3bAYMOej_gC_Au:-NEcUW4w2uWg1jjlTzIb:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/actActor.h#L146)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/KingSystem/ActorSystem/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc78V03hD3Unq_yrWu:-NEcU_voEkxAmgCoauw3:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/CMakeLists.txt#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Could you revert the indentation changes?
</blockquote></details>

Done.
___
*[`src/KingSystem/Physics/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7Ebr7L-YzKxMgtoo:-NEcUaafAixG3QAtxPkl:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/Physics/CMakeLists.txt#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.
___
*[`src/KingSystem/Physics/System/physInstanceSet.h` line 77 at r2](https://reviewable.io/reviews/zeldaret/botw/104#-NEc8lbY0fyAotYzy-a1:-NEcUbP_BZgdQv_rDkNK:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/3048531650109843d66d01eadcac4ef9e4181aae/src/KingSystem/Physics/System/physInstanceSet.h#L77)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Can we change this to return a `RigidBody*`?
</blockquote></details>

Done.
___
*[`src/KingSystem/System/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc7LiF4_p8G57gr4bw:-NEcUdCa1sbJJLqxjDUz:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/System/CMakeLists.txt#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
> Reviewed 29 of 31 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @notyourav)

___
*[`src/KingSystem/ActorSystem/CMakeLists.txt` line 2 at r1](https://reviewable.io/reviews/zeldaret/botw/104#-NEc78V03hD3Unq_yrWu:-NEdlFuk55uWpTpfBmr-:b15a363) ([raw file](https://github.com/zeldaret/botw/blob/52e8f572d0951e64ce513c019d46bd208455ae4c/src/KingSystem/ActorSystem/CMakeLists.txt#L2)):*
<details><summary><i>Previously, notyourav wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Huh, looks like I used 2 spaces in CMake files for some reason :thinking:

4 is probably better to stay consistent with the C++ source files

**Pull request merged**
