### PR TITLE
Support bone resource

### PR DESCRIPTION
**Pull request by MonsterDruide1**
Quite a lot of mismatches here...
1. `SupportBoneResource::init`: Mismatches in the creation part of `connectionCurveList`
2. `SupportBoneResource::doSomethingAboutConnectionCurves` (maybe also `someHelperInterpolationForConnectionCurvesSomething`): Float operations being picky about the order of commands
3. `SupportBoneResource::BaseBone::postRead_`: Due to seadQuat::normalize() mismatch, this function does not match.

Other notes:
- `.gitmodules` was updated to point to my (updated) `sead` library. When everything matches, a PR can be made there and the original repo used instead.
- Functions should obviously still be renamed to match their functionality

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)

### CODE REVIEW

**Comment by leoetlino** [comment]
isnan stuff should be fixed now that we are actually using musl (instead of glibc). I'll take a look soon

**Comment by MonsterDruide1** [comment]
1. `SupportBoneResource::Init` is fixed: perfect match now.
2. `doSomethingAboutConnectionCurves` has been fixed and renamed to `getInterpolatedConnectionCurve`, the inline helper function (`someHelperInterpolationForConnectionCurvesSomething`) has been renamed to `cubicHermiteInterpolate`
3. This issue is still open... I can't figure out or even have a starting point for fixing this one. It is the only remaining issue of this PR.

**Comment by leoetlino** [comment]
nice, so _ZN4ksys4phys19SupportBoneResource8BaseBone9postRead_Ev is the only one that doesn't match. I'll check the Quat stuff

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: all files reviewed, 16 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 19 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2njDeAggmk3VspN2U:-Mg2njDeAggmk3VspN2V:b-tlauit) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L19)):*
> ```objc
> 
>         agl::utl::Parameter<sead::FixedSafeString<64>> name;
>     };
> ```

Having new lines between the struct definitions would make this more readable.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 87 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nd1u0k-dA1f9UJFQ:-Mg2nd1u0k-dA1f9UJFR:bljwrku) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L87)):*
> ```objc
> 
> private:
>     agl::utl::ParameterObj supportBoneHeader;
> ```

m prefix for member variables
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 89 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nX6Z5bsIFc6LqJjK:-Mg2nX6Z5bsIFc6LqJjL:b3s2wa5) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L89)):*
> ```objc
>     agl::utl::ParameterObj supportBoneHeader;
>     agl::utl::ParameterList supportBoneData;
>     // int gap_260;  // unknown purpose, 8 bytes
> ```

Probably just the ParameterList struct being 8 bytes too small in IDA. Can you remove this line?
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 114 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2noQe-4gxP9uynMuP:-Mg2noQe-4gxP9uynMuQ:bz9rqmt) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L114)):*
> ```objc
> KSYS_CHECK_SIZE_NX150(SupportBoneResource, 0x5B0);
> 
> }  // namespace ksys::phys
> ```

trailing newline
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2oEg71kZFcV3zZuL_:b-1jdpvz) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
> ```cpp
> #include "KingSystem/Physics/SupportBone/physSupportBoneResource.h"
> #include <math.h>
> ```

C++ code should include `<cmath>` (math.h is deprecated in C++)
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 26 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nqjz77poVgCjHbKu:-Mg2nqjz77poVgCjHbKv:b-d5m9vp) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L26)):*
> ```cpp
>       outputSingleNum(0, "output_single_num", "output_single_num", &supportBoneHeader),
>       outputDoubleNum(0, "output_double_num", "output_double_num", &supportBoneHeader),
>       mainBoneNum(0, "main_bone_num", "main_bone__num", &supportBoneHeader),
> ```

might be worth having a "[sic]" comment above this line (because the `main_bone__num` looks like a mistake but is actually correct; Nintendo messed up the names)
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 58 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p50tB4h8zvd6bRoi:-Mg2p50tB4h8zvd6bRoj:b-v0l7bh) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L58)):*
> ```cpp
>     sead::Vector2f slope_intercept = connectionLinearBuffer[a2].slope_intercept.ref();
>     float result = slope_intercept.x * a3 + slope_intercept.y;
>     return isnan(result) ? 0.0f : result;
> ```

std::isnan
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 99 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oNI246NRCKhBwcrj:-Mg2oNI246NRCKhBwcrk:bcbxrew) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L99)):*
> ```cpp
>             connectionLinearBuffer[i].bone_attribute.init(
>                 0, "bone_attribute", "bone_attribute",
>                 &connectionLinearBuffer[i]);  // initiated with 0 instead of -1
> ```

typo: "initialised"
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 145 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oQwk8be0UY6q1E_h:-Mg2oQwk8be0UY6q1E_i:b-w4wb4i) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L145)):*
> ```cpp
>     if (output_double_num > 0) {
>         supportBoneData.addList(&outputDoubleList, "output_double_list");
>         // outputDoubleBuffer.allocBufferAssert(output_double_num, heap);
> ```

Code that's been commented out like this should be removed
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 184 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oY82-9LtWPIu1pFw:-Mg2oY83Exnokpy72miM:b-vu08dp) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L184)):*
> ```cpp
> }
> 
> float inline cubicHermiteInterpolate(const sead::Vector4f& key1, const sead::Vector4f& key2,
> ```

While syntaxically correct, this is more commonly written as `inline float` (kind of like the order of adjectives in the English language...)
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 201 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oq42749rr1GQLw6u:-Mg2oq42749rr1GQLw6v:b-f0ijsd) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L201)):*
> ```cpp
> 
> float SupportBoneResource::getInterpolatedConnectionCurve(u32 index, float lookup) {
>     auto& connectionCurve = connectionCurveBuffer[index];
> ```

connection_curve
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 206 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2owAR4tvsf-4tzHpJ:-Mg2owAR4tvsf-4tzHpK:bj37372) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L206)):*
> ```cpp
>     float x1 = connectionCurve.key1->x;  // middle (0 in most cases)
>     float x2 = connectionCurve.key2->x;  // highest
>     if (x0 == lookup)
> ```

All the conditional branches here should be braced
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 223 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2otZnDmdhOqXQcH_Y:-Mg2otZnDmdhOqXQcH_Z:b-jb49s9) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L223)):*
> ```cpp
>             cubicHermiteInterpolate(connectionCurve.key1.ref(), connectionCurve.key2.ref(), lookup);
>     } else {
>         if (!connectionCurve.constant_out.ref())
> ```

can't this be an `else if` as well?
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 229 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p3Ya1UFEWFYCzc93:-Mg2p3Ya1UFEWFYCzc94:b-v0l7bh) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L229)):*
> ```cpp
>     }
> 
>     return isnan(result) ? 0.0f : result;
> ```

std::isnan
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResourceMainBone.cpp, line 8 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p90U-CIhde8VIm9w:-Mg2p90U-CIhde8VIm9x:b-h4583q) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResourceMainBone.cpp#L8)):*
> ```cpp
> SupportBoneResource::BaseBone::~BaseBone() = default;
> 
> }  // namespace ksys::phys
> ```

trailing newline please (it should be possible to configure VSCode to do this automatically)
___
*[tools/diff.py, line 53 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2pEbz56BSlONqV4w1:-Mg2pEbz56BSlONqV4w2:b-u5ixwm) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/tools/diff.py#L53)):*
> ```Python
>     utils.fail(
>         f"unknown function '{args.function}'\nfor constructors and destructors, list the complete object constructor (C1) or destructor (D1)")
>         
> ```

This accidental change should be reverted

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: 4 of 8 files reviewed, 16 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 19 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2njDeAggmk3VspN2U:-Mg2rVzSEgDNGsyM2FET:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Having new lines between the struct definitions would make this more readable.
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 87 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nd1u0k-dA1f9UJFQ:-Mg2sarn3jLroDmpXxKU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L87)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

m prefix for member variables
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 89 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nX6Z5bsIFc6LqJjK:-Mg2sbPGDuz3IbwtNwTi:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L89)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Probably just the ParameterList struct being 8 bytes too small in IDA. Can you remove this line?
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.h, line 114 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2noQe-4gxP9uynMuP:-Mg2sg2T1ItFSlmE4s-6:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.h#L114)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

trailing newline
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2t5VJ-W7s08fvNGq0:b18avi5) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

C++ code should include `<cmath>` (math.h is deprecated in C++)
</blockquote></details>

Is actually not needed, as `std::isnan` is used instead. 
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 58 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p50tB4h8zvd6bRoi:-Mg2tNhg-ZscheXxfMaE:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L58)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

std::isnan
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 99 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oNI246NRCKhBwcrj:-Mg2tTDk6RWIqomN84Yu:b-1g48ln) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L99)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

typo: "initialised"
</blockquote></details>

Actually not a typo, just me not knowing proper english words! 😜
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 145 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oQwk8be0UY6q1E_h:-Mg2tjf75CF1V9vQDtKW:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L145)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Code that's been commented out like this should be removed
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 184 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oY82-9LtWPIu1pFw:-Mg2ttqj2rJRUIDUWpaA:b7dpoe4) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L184)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

While syntaxically correct, this is more commonly written as `inline float` (kind of like the order of adjectives in the English language...)
</blockquote></details>

Done. Should this function also be added to the header?
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 201 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oq42749rr1GQLw6u:-Mg2u0VaAXx1X0MrBWTd:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L201)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

connection_curve
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 206 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2owAR4tvsf-4tzHpJ:-Mg2uF-g2y1GzXGSXz2U:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L206)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

All the conditional branches here should be braced
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 223 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2otZnDmdhOqXQcH_Y:-Mg2uFNP7j7huL21-eqn:b-ek0um1) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L223)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

can't this be an `else if` as well?
</blockquote></details>

Could be... but it made more sense to me to make it like this, as all branches before use a conditional by comparing `lookup` to some `x`-value, whereas this one works with something completely different.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 229 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p3Ya1UFEWFYCzc93:-Mg2uSeUAnrhLmBb6I0r:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L229)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

std::isnan
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResourceMainBone.cpp, line 8 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2p90U-CIhde8VIm9w:-Mg2uZEKA0ommXsBYWA6:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResourceMainBone.cpp#L8)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

trailing newline please (it should be possible to configure VSCode to do this automatically)
</blockquote></details>

Done.
___
*[tools/diff.py, line 53 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2pEbz56BSlONqV4w1:-Mg2uljIEIJTuRWweINP:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/tools/diff.py#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This accidental change should be reverted
</blockquote></details>

Done.

**Review by leoetlino — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2wUGD-tifEJRpULF9:b7159j3) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Is actually not needed, as `std::isnan` is used instead. 
</blockquote></details>

It is still needed, because std::isnan is declared in `<cmath>` :P
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 26 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nqjz77poVgCjHbKu:-Mg2waUK8ShaToedL_rF:b-mgqjf8) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

might be worth having a "[sic]" comment above this line (because the `main_bone__num` looks like a mistake but is actually correct; Nintendo messed up the names)
</blockquote></details>

to clarify, something like `// sic` would be fine
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 184 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oY82-9LtWPIu1pFw:-Mg2whFs-GddnVtVIMH3:bo0ay6v) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L184)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. Should this function also be added to the header?
</blockquote></details>

nope (unless we find out it's used somewhere else)

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2xCJo9ID3f2gV8s8D:b7gmfsb) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

It is still needed, because std::isnan is declared in `<cmath>` :P
</blockquote></details>

It compiles without manually including `<cmath>`, should it be included anyways? Probably already included in some other included file...

**Review by leoetlino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2xbzl2ITLLN_fvcNy:b-7oo8da) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

It compiles without manually including `<cmath>`, should it be included anyways? Probably already included in some other included file...
</blockquote></details>

Yes, a good practice is to avoid indirect includes.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 2 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2oEg71kZFcV3zZuLZ:-Mg2y35o2gV7YMIzhAM8:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L2)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Yes, a good practice is to avoid indirect includes.
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp, line 26 at r4](https://reviewable.io/reviews/zeldaret/botw/45#-Mg2nqjz77poVgCjHbKu:-Mg2y2Nz-gVgS8JJZ3zX:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/9def2d70d1a0bccf7d2804f58c2e720d043a998e/src/KingSystem/Physics/SupportBone/physSupportBoneResource.cpp#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

to clarify, something like `// sic` would be fine
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
:lgtm:

I'll merge after the formatting issues are fixed

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45#-:-Mg2ycibB7sNu7xfEfn_:bsmj7u9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
