### PR TITLE
Implemented DebugFinder

### PR DESCRIPTION
**Pull request by iTNTPiston**
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/58)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/58)* status: all files reviewed, 3 unresolved discussions (waiting on @iTNTPiston)

___
*[data/uking_functions.csv, line 0 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MgjLOij4cSvRRs5vNNP:-MgjLOij4cSvRRs5vNNQ:b7vj7q8) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/data/uking_functions.csv#L0)):*
the DebugFinder dtor functions should be listed as well
___
*[src/KingSystem/System/DebugFinder.h, line 22 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MgjLTv35ftNTP_GYKjs:-MgjLTv35ftNTP_GYKjt:bz9rqmt) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/src/KingSystem/System/DebugFinder.h#L22)):*
> ```objc
> };
> 
> }  // namespace ksys
> ```

trailing newline
___
*[src/KingSystem/System/DebugFinder.cpp, line 11 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MgjLVhU60ItNmtj1Vqj:-MgjLVhU60ItNmtj1Vqk:bz9rqmt) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/src/KingSystem/System/DebugFinder.cpp#L11)):*
> ```cpp
> void DebugFinder::init(sead::Heap* heap) {}
> 
> }  // namespace ksys
> ```

trailing newline

**Comment by leoetlino** [comment]
There have been some recent tool updates, so if you are getting weird build failures when you update this PR, please try again after rebasing your branch on latest master.

**Review by leoetlino — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/58)* status: all files reviewed, 2 unresolved discussions (waiting on @iTNTPiston)

___
*[src/KingSystem/System/DebugFinder.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MhoalxXElqImczJOVR9:-MhoalxXElqImczJOVRA:b3z43vv) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/src/KingSystem/System/DebugFinder.h#L14)):*
> ```objc
> 
> public:
>     void init(sead::Heap* heap);
> ```

Any reason you removed init?

**Review by iTNTPiston — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/58)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[data/uking_functions.csv, line  at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MgjLOij4cSvRRs5vNNP:-MhodQ6NCKTcJmD66d_P:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/data/uking_functions.csv#L)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the DebugFinder dtor functions should be listed as well
</blockquote></details>

Done.
___
*[src/KingSystem/System/DebugFinder.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MhoalxXElqImczJOVR9:-MhodZcjDOGIOkLzkQt2:b-1zeiw) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/src/KingSystem/System/DebugFinder.h#L14)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Any reason you removed init?
</blockquote></details>

There was an empty function that I thought was an empty init, but now we know it's an empty dtor

**Review by leoetlino — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iTNTPiston)

___
*[src/KingSystem/System/DebugFinder.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/58#-MhoalxXElqImczJOVR9:-MhodwiZBYMi24_slRiz:b-ugvacs) ([raw file](https://github.com/zeldaret/botw/blob/b502476d9632379379b28bc726be85c8a7a1eb68/src/KingSystem/System/DebugFinder.h#L14)):*
<details><summary><i>Previously, iTNTPiston (Michael) wrote…</i></summary><blockquote>

There was an empty function that I thought was an empty init, but now we know it's an empty dtor
</blockquote></details>

Ah, that makes sense.

**Pull request merged**
