### PR TITLE
ksys::ProductReporter

### PR DESCRIPTION
**Pull request by ConorBobbleHat**
Some very minor differences left in ProductReporter::incrementSceneAndRomWorkTime (as a result of my imperfect member function-ification). It should be functionally equivalent, at least.

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/93)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/93)* status: all files reviewed, 6 unresolved discussions (waiting on @ConorBobbleHat)

___
*[`src/KingSystem/Sound/sndMgr.h` line 22 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tUtD0BpzunTTzAMI9:-N4tUtD0BpzunTTzAMIA:bre4o7) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/Sound/sndMgr.h#L22)):*
> ```objc
> 
> public:
>     u8 _0[0x248];
> ```

`_28[0x220]` (because you already have the vtable pointer at offset 0 and the disposer at offset 0x20)
___
*[`src/KingSystem/System/ProductReporter.h` line 25 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tV5YR3R3KZV7Dgk3K:-N4tV5YR3R3KZV7Dgk3L:bl3gs06) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/System/ProductReporter.h#L25)):*
> ```objc
> };
> 
> static WorkTimes sWorkTimes;
> ```

This variable definition should be moved to the .cpp
___
*[`src/KingSystem/System/ProductReporter.h` line 72 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tX7VQBTwbWqsZDvSb:-N4tX7VR67BZSxTpf8ET:ben09c1) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/System/ProductReporter.h#L72)):*
> ```objc
>     void getFlag(u32 key, s32* value) {
>         gdt::Manager::instance()->getS32(mGameDataHandles[key], value);
>     };
> ```

no need for semicolons after a function definition
___
*[`src/KingSystem/System/ProductReporter.cpp` line 34 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tXCQI2_N-wpEFIs6m:-N4tXCQI2_N-wpEFIs6n:bovz91q) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/System/ProductReporter.cpp#L34)):*
> ```cpp
> 
> void ProductReporter::init(sead::Heap* heap) {
>     if (!mIsInitalized) {
> ```

```cpp
if (mIsInitialized)
  return;
```

https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code
___
*[`src/KingSystem/System/ProductReporter.cpp` line 113 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tXaT93qgV6v2WTuHw:-N4tXaT93qgV6v2WTuHx:b-7qqe9u) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/System/ProductReporter.cpp#L113)):*
> ```cpp
> bool ProductReporter::incrementSceneAndRomWorkTime() {
>     if (map::PlacementMgr::instance() == nullptr)
>         return 0;
> ```

false
___
*[`src/KingSystem/System/ProductReporter.cpp` line 127 at r1](https://reviewable.io/reviews/zeldaret/botw/93#-N4tXjtl1_-gqEqM49lA:-N4tXjtl1_-gqEqM49lB:b-7qqe9u) ([raw file](https://github.com/zeldaret/botw/blob/144bf948827861622925bd0e7406a0f0cd9ca83c/src/KingSystem/System/ProductReporter.cpp#L127)):*
> ```cpp
> 
>     if (!(mCameraIdleTimer < 300.0f))
>         return 0;
> ```

false

**Comment by ConorBobbleHat** [comment]
That should be everything. I tweaked the first suggested fix - 0x248 as an padding length does account for the vtable pointer and disposer; I misinterpreted the naming conventions for padding fields first time round.

**Review by leoetlino — APPROVED** [review]
:lgtm:

I'll try to figure out if something can be done to match that increment function with member functions

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/93#-:-N4vnQ6C4Hp-rEK6_33R:b-1ixc9g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ConorBobbleHat)

**Comment by ConorBobbleHat** [comment]
Thanks!

**Comment by leoetlino** [comment]
It looks like the lambda's `this` capture causes an extra memory load which prevents LLVM from reordering the FlagHandle load. This happens very early during IR optimisation (even before the function inlining pass for _ZN4ksys15ProductReporter28incrementSceneAndRomWorkTimeEv). Oh well, I guess turning getFlag/setFlag/increment into lambdas isn't too weird, considering that those functions are only used in that one incrementSceneAndRomWorkTime function.

**Pull request merged**
