### PR TITLE
tools: Move to separate repo

### PR DESCRIPTION
**Pull request by MonsterDruide1**
All common `tools`, that can be shared between multiple NX-decomp projects have been moved to `tools/common` and are now included using a submodule. This means that also the dependency of `toolchain/musl`, `tools/asm-differ` and `tools/nx-decomp-tools-binaries` is indirect, as those are included in the common `tools` repo instead.

As the `tools`, scripts and programs need small adjustments between different repo (file paths/names, ...), a config file has been added to `tools/config.toml`, containing all values that change between repos. 

This also affects the `botw-check`-program: It has been moved to `tools/check` now instead and is automatically built by `tools/setup.py`. It will also read the `config.toml` and operate accordingly, so the binary doesn't need to change between different repos and games.

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 40 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 40 of 43 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjRVJgDsZ0-pJmWNp8:b-sjlq5m) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
> ```ignore
> 
> # Tooling
> /toolchain/clang/
> ```

This should be reverted. The toolchain is *explicitly* not shared between games (in general, unless the games were released during the same time period and happened to use the same LLVM version).
___
*[.gitmodules, line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRfSQA2aJ9nBRx_ex:-MgjRfSQA2aJ9nBRx_ey:b-thnm33) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitmodules#L16)):*
> ```gitconfig
> 	path = lib/EventFlow
> 	url = https://github.com/open-ead/EventFlow
> [submodule "toolchain/musl"]
> ```

Strong -1 on this as well. While updates to the standard C library are infrequent, they can happen and there's no reason for making it part of the common repo for the same reason the compiler shouldn't be in the common repo.
___
*[toolchain/ToolchainNX64.cmake, line 1 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjSuCWEi89zmeMwyoi:-MgjSuCX9sdbmh-GZM9e:b-f7kgsb) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/toolchain/ToolchainNX64.cmake#L1)):*
> ```CMake
> if (DEFINED ENV{UKING_CLANG})
> ```

The toolchain file shouldn't be common either for several reasons:

* Build options are likely to vary depending on the game *and* toolchain version (for instance, at some point Nintendo started shipping their toolchain with default options that cause symbols to not be exported anymore). Pretty sure not all games use -mno-implicit-float either.
* The toolchain file still references U-King.
* Some LLVM versions require extra attention to make LLD work, so enabling it by default *and* doing so for all games (by making this common) is not a good idea.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 38 of 43 files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjZOa_DqoB2VtrRdWN:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be reverted. The toolchain is *explicitly* not shared between games (in general, unless the games were released during the same time period and happened to use the same LLVM version).
</blockquote></details>

Done.
___
*[.gitmodules, line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRfSQA2aJ9nBRx_ex:-MgjZPfU9tcvPfDo_eOB:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitmodules#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Strong -1 on this as well. While updates to the standard C library are infrequent, they can happen and there's no reason for making it part of the common repo for the same reason the compiler shouldn't be in the common repo.
</blockquote></details>

Done.
___
*[toolchain/ToolchainNX64.cmake, line 1 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjSuCWEi89zmeMwyoi:-MgjZXp6-JKqo2IiFi8o:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/toolchain/ToolchainNX64.cmake#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

The toolchain file shouldn't be common either for several reasons:

* Build options are likely to vary depending on the game *and* toolchain version (for instance, at some point Nintendo started shipping their toolchain with default options that cause symbols to not be exported anymore). Pretty sure not all games use -mno-implicit-float either.
* The toolchain file still references U-King.
* Some LLVM versions require extra attention to make LLD work, so enabling it by default *and* doing so for all games (by making this common) is not a good idea.
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjaY1q7lQzC0bBmW3P:b-acc5ho) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

setup.py should be extracting the compiler to /toolchain/clang, not /toolchain/clang{version} (setup_common.py) or /toolchain/clang-{version} (as this .gitignore suggests). Having the version number just complicates things for seemingly no good reason and notably breaks the CMake toolchain file.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: all files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjbujCCvgvHf77_Llp:bk8bmzi) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

setup.py should be extracting the compiler to /toolchain/clang, not /toolchain/clang{version} (setup_common.py) or /toolchain/clang-{version} (as this .gitignore suggests). Having the version number just complicates things for seemingly no good reason and notably breaks the CMake toolchain file.
</blockquote></details>

It does make sense for other games and generally looks a bit cleaner to me. For example Mario Odyssey needs both `3.9.1` and `4.0.1` available, and saving both to `clang` without any version number will override one of the two. But right - Toolchain still needs to be changed, if this change is accepted.

**Review by leoetlino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjchzJ7hCgM4aUCBsF:b-mnxm20) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

It does make sense for other games and generally looks a bit cleaner to me. For example Mario Odyssey needs both `3.9.1` and `4.0.1` available, and saving both to `clang` without any version number will override one of the two. But right - Toolchain still needs to be changed, if this change is accepted.
</blockquote></details>

Okay, that makes sense then. Both the gitignore and the toolchain file need to be fixed though.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 41 of 43 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MgjnKNR6Cj3oIq1YES7:b-pd7zgr) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Okay, that makes sense then. Both the gitignore and the toolchain file need to be fixed though.
</blockquote></details>

Done. What in the `.gitignore` needs to be fixed?

**Review by leoetlino — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: all files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-Mgjnaq54gc7ma4DTaRr:b-dm6h3o) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. What in the `.gitignore` needs to be fixed?
</blockquote></details>

Either the gitignore or setup_common.py needs to be updated so that the paths are consistent with one another (`clang-4.0.1` or `clang4.0.1`).

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[.gitignore, line 43 at r1](https://reviewable.io/reviews/zeldaret/botw/59#-MgjRVJgDsZ0-pJmWNp7:-MglSdBh0hNG6WqsvV7i:b-7sqr10) ([raw file](https://github.com/zeldaret/botw/blob/802be64d8e41917b002cd9c21c500c91f9b96c93/.gitignore#L43)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Either the gitignore or setup_common.py needs to be updated so that the paths are consistent with one another (`clang-4.0.1` or `clang4.0.1`).
</blockquote></details>

Done. Fixed the path in `setup_common.py`.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 42 of 43 files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[.gitmodules, line 15 at r3](https://reviewable.io/reviews/zeldaret/botw/59#-MglTNzw5_LEvsWzDgBS:-MglTNzw5_LEvsWzDgBT:b-460qgz) ([raw file](https://github.com/zeldaret/botw/blob/489c6589696076571325b2be21c0475a5014696e/.gitmodules#L15)):*
> ```gitconfig
> [submodule "tools/common"]
> 	path = tools/common
> 	url = https://github.com/MonsterDruide1/nx-decomp-tools
> ```

Should be changed to official repo (`open-ead`) before being merged.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59)* status: 41 of 43 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[.gitmodules, line 15 at r3](https://reviewable.io/reviews/zeldaret/botw/59#-MglTNzw5_LEvsWzDgBS:-MglgH3s9v2rxe81Lp5j:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/489c6589696076571325b2be21c0475a5014696e/.gitmodules#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should be changed to official repo (`open-ead`) before being merged.
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/59#-:-MglhKiB7YH-UcdX-p62:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
