### PR TITLE
Decompile most of E3mgr

### PR DESCRIPTION
**Pull request by louist103**
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/101)

### CODE REVIEW

**Comment by ThePixelGamer** [comment]
Can you exclude updating the lib submodules for this PR? Seems there's an error with the sead lib (@leoetlino: it's related to the projection classes you pulled)

**Comment by leoetlino** [comment]
The sead build issue has been fixed now. This should build fine after the PR is rebased on master.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/101)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @leoetlino and @louist103)

___
*[`src/Game/CMakeLists.txt` line 14 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbW7HDuG2K2TzJfi7:-NAWbW7HDuG2K2TzJfi8:b1tsngt) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/CMakeLists.txt#L14)):*
> ```CMake
>   gameStageInfo.cpp
>   gameStageInfo.h
>   E3MGR.cpp
> ```

I think we should call this E3Mgr (or gameE3Mgr.cpp) as Nintendo never writes Mgr (manager) all in uppercase.
___
*[`src/Game/CMakeLists.txt` line 15 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbeCC3uAMmxmto3F-:-NAWbeCC3uAMmxmto3F0:b-14dl7e) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/CMakeLists.txt#L15)):*
> ```CMake
>   gameStageInfo.h
>   E3MGR.cpp
>   E3MGR.hpp
> ```

Like lots of C++ projects, we use .h for C++ header files, not .hpp.
___
*[`src/Game/E3MGR.hpp` line 29 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbsKL7FHuR31u_kxq:-NAWbsKL7FHuR31u_kxr:bb7w32q) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.hpp#L29)):*
> ```cpp
>     void clear28();
>     void set28();
>     bool __auto1();
> ```

These should be given more meaningful names if possible (if not, use e.g. `x_1` instead of `__auto` because names containing double underscores are reserved. Using reserved names in user code is UB.

Also potentially useful (but not enforced): comments above unimplemented functions to indicate where they can be found. See https://github.com/zeldaret/botw/blob/16e712b89db787663729f72d0fb36b40f8e21bc2/src/KingSystem/Physics/RigidBody/physRigidBody.h#L193 for an example.
___
*[`src/Game/E3MGR.hpp` line 37 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWcRVz-y0-z7nif3fa:-NAWcRVz-y0-z7nif3fb:b-k9ppi7) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.hpp#L37)):*
> ```cpp
>     void __auto8(bool a2);
> 
>     bool isRID_Demo_and_a1x28_is_one();
> ```

camelCase
___
*[`src/Game/E3MGR.hpp` line 83 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWctzF5UQJhKSiaiv6:-NAWctzF5UQJhKSiaiv7:b4o96eg) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.hpp#L83)):*
> ```cpp
>     ksys::res::Handle handle;
> 
>     u32 mDemoStage = 0xFFFFFFFF;
> ```

Looks like this might be a signed integer? 0xffffffff is -1.
___
*[`src/Game/E3MGR.cpp` line 65 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWd0JQB3dZXpr1h8zw:-NAWd0JQB3dZXpr1h8zx:bghoglt) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.cpp#L65)):*
> ```cpp
> 
> bool E3Mgr::__auto1() {
>     if (E3Mgr::isDemoMode() && mDemoMode == 0) {
> ```

`if (a && b) return c; else return false;` can be written more concisely as `return a && b && c`.
___
*[`src/Game/E3MGR.cpp` line 170 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWdCk69jDW_cSjcTh1:-NAWdCk69jDW_cSjcTh2:bgr8z5p) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.cpp#L170)):*
> ```cpp
> 
> //! TODO : this should be a real struct
> typedef struct dummy {
> ```

no need to typedef structs like that, as structs are already type names and you do not need to write `struct` to refer to structs in C++
___
*[`src/KingSystem/Map/mapPlacementMgr.h` line 81 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWdd0E30QZDZwWMBGB:-NAWdd0FBzOKzkzhpZn7:b-5gf7um) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/KingSystem/Map/mapPlacementMgr.h#L81)):*
> ```objc
>     bool isGrudgeMerge() const { return sFlags.isOn(MgrStaticFlags::GrudgeMerge); }
> 
>     static sead::TypedBitFlag<MgrStaticFlags, u16> sFlags;
> ```

Good catch, this definitely looks like a 16-bit variable :)

**Comment by leoetlino** [comment]
Please fix these warnings: https://ci.botw.link/#/builders/3/builds/58

Feel free to ignore `constructor does not initialize these fields: mSingletonDisposerBuf_ [cppcoreguidelines-pro-type-member-init]` though

**Review by leoetlino — CHANGES_REQUESTED** [review]
So sorry for the delayed review (was sick last week and been trying to catch up since).

This mostly looks good to me now, just a few minor things left

> Reviewed 1 of 5 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/101#-:-NDsEcTP0KRTDyxcyBEp:b-6jjqhj)* status: all files reviewed, 3 unresolved discussions (waiting on @louist103)

___
*[`src/Game/CMakeLists.txt` line 15 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbeCC3uAMmxmto3F-:-NDsEAQh3ysvGiIYiB4d:bgilayz) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/CMakeLists.txt#L15)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Like lots of C++ projects, we use .h for C++ header files, not .hpp.
</blockquote></details>

.hpp should be .h
___
*[`src/Game/E3MGR.cpp` line 170 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWdCk69jDW_cSjcTh1:-NDsEOu-8n9f2gv-cJel:b-1xqy6g) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.cpp#L170)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

no need to typedef structs like that, as structs are already type names and you do not need to write `struct` to refer to structs in C++
</blockquote></details>

the type alias does not seem to be useful here as you could just declare the struct directly: 
```
struct Dummy {
...
};
```
___
*[`src/Game/E3Mgr.cpp` line 185 at r5](https://reviewable.io/reviews/zeldaret/botw/101#-NDsEaOD1otoELLqX7fS:-NDsEaOD1otoELLqX7fT:bso67yn) ([raw file](https://github.com/zeldaret/botw/blob/bf3d425ad6ee300522418bebbd10f05a558c727d/src/Game/E3Mgr.cpp#L185)):*
> ```cpp
>     if (isDemo) {
>         if (test)
>             (test->a00) |= 0x40;
> ```

No need for the parens.

**Review by louist103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/101)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[`src/Game/CMakeLists.txt` line 14 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbW7HDuG2K2TzJfi7:-NA_iDSx3iHt6nFphmNo:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/CMakeLists.txt#L14)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think we should call this E3Mgr (or gameE3Mgr.cpp) as Nintendo never writes Mgr (manager) all in uppercase.
</blockquote></details>

Done.
___
*[`src/Game/CMakeLists.txt` line 15 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWbeCC3uAMmxmto3F-:-NDtM4551WesSVHw_H2s:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/CMakeLists.txt#L15)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

.hpp should be .h
</blockquote></details>

Done.
___
*[`src/Game/E3MGR.hpp` line 37 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWcRVz-y0-z7nif3fa:-NA_iT9p5Ke3w3dWyjAy:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.hpp#L37)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

camelCase
</blockquote></details>

Done.
___
*[`src/Game/E3MGR.cpp` line 170 at r3](https://reviewable.io/reviews/zeldaret/botw/101#-NAWdCk69jDW_cSjcTh1:-NDtP9nw9tfjuyO9OjfL:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/7e9bd8a1a6e22ceb6254159ce707df71afbb8e60/src/Game/E3MGR.cpp#L170)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the type alias does not seem to be useful here as you could just declare the struct directly: 
```
struct Dummy {
...
};
```
</blockquote></details>

Done.
___
*[`src/Game/E3Mgr.cpp` line 185 at r5](https://reviewable.io/reviews/zeldaret/botw/101#-NDsEaOD1otoELLqX7fS:-NDtPAkp2CoVOidhcZJq:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/bf3d425ad6ee300522418bebbd10f05a558c727d/src/Game/E3Mgr.cpp#L185)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

No need for the parens.
</blockquote></details>

Done.

**Comment by ThePixelGamer** [comment]
The sead submodule needs to be updated to at least [79f528b](https://github.com/open-ead/sead/tree/79f528be96a3d7c844847ab6371e0ae6b38c83c7)

**Review by leoetlino — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @louist103)

**Pull request merged**
