### PR TITLE
Implement CookingMgr class

### PR DESCRIPTION
**Pull request by TheGreatB3**
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/113)

### CODE REVIEW

**Review by leoetlino — COMMENTED** [review]
> Reviewed 14 of 16 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/113)* status: 15 of 16 files reviewed, 17 unresolved discussions (waiting on @TheGreatB3)

___
*[`src/Game/AI/Action/actionSetCookItemInDemo.cpp` line 18 at r1](https://reviewable.io/reviews/zeldaret/botw/113#-NMclFrY0LnNH2fBzvjc:-NMclFrZ6t73tz8ICWds:b-ijpbmh) ([raw file](https://github.com/zeldaret/botw/blob/56deac33b8686c7ab621cb82ec56e4054d3dbf8d/src/Game/AI/Action/actionSetCookItemInDemo.cpp#L18)):*
> ```cpp
>     CookItem cook_item{};
> 
>     CookingMgr::BoostArg boost_arg;  // NOLINT(cppcoreguidelines-pro-type-member-init)
> ```

IMO it would be preferable to set the two members to false by default (by adding default member initialisers) so we can avoid having to silence the lint warning manually
___
*[`src/Game/AI/AI/aiCookPotRoot.cpp` line 59 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhfjhFDSgf4TjhBzEK:-NMhfjhG-SHqnTwxSXr0:b-7t4fpm) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/AI/AI/aiCookPotRoot.cpp#L59)):*
> ```cpp
>                     const int num_ingredients = 5;  // TODO
>                     _48 = true;
>                     CookingMgr* cooking_mgr = CookingMgr::instance();
> ```

auto*
___
*[`src/Game/AI/AI/aiCookPotRoot.cpp` line 63 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhfo9g4Vzh9cfmfF4p:-NMhfo9g4Vzh9cfmfF4q:b-eqoe6a) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/AI/AI/aiCookPotRoot.cpp#L63)):*
> ```cpp
>                                                   mCookItem);
> 
>                     CookingMgr::BoostArg boost_arg{false, true};
> ```

Consider using designated initialisers here (even though they are not standard prior to C++20, they improve readability a lot)
___
*[`src/Game/Cooking/cookManager.h` line 9 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhgq-n1vTxy2Y3NmyL:-NMhgq-n1vTxy2Y3NmyM:b-99ozqk) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.h#L9)):*
> ```objc
> #include "KingSystem/Utils/Byaml/Byaml.h"
> #include "KingSystem/Utils/Types.h"
> #include "container/seadBuffer.h"
> ```

`#include <...>`
___
*[`src/Game/Cooking/cookManager.h` line 79 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhgLHZ-mkO2cy_eqGe:-NMhgLHZ-mkO2cy_eqGf:b-mzychk) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.h#L79)):*
> ```objc
>     void cookCalcCritBoost(const IngredientArray& ingredients, CookItem& cook_item,
>                            const BoostArg* boost_arg) const;
>     void cookHandleMonsterExtract([[maybe_unused]] const IngredientArray& ingredients,
> ```

I think the [[maybe_unused]] attribute should probably only be in the .cpp
___
*[`src/Game/Cooking/cookManager.cpp` line 82 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhAEoC_gtjahaJMAo:-NMhhAEoC_gtjahaJMAp:b-vstyvi) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L82)):*
> ```cpp
> 
> CookingMgr::~CookingMgr() {
>     if (mConfig) {
> ```

`util::safeDelete(mConfig);`
___
*[`src/Game/Cooking/cookManager.cpp` line 96 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhqoY88pTwosOOuh3:-NMhhqoY88pTwosOOuh4:b-y6i210) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L96)):*
> ```cpp
>         // Dubious food
>         cook_item.effect_time = 0;
>         const f32 min_recovery = (f32)(s32)mFailActorLifeRecover;
> ```

Those casts are a bit ugly – consider hiding them behind a getter function (especially as cookFailForMissingConfig has the same casts)
___
*[`src/Game/Cooking/cookManager.cpp` line 98 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhYo_3dfBTJbn_caC:-NMhhYo_3dfBTJbn_caD:b-frbg5) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L98)):*
> ```cpp
>         const f32 min_recovery = (f32)(s32)mFailActorLifeRecover;
>         life_recover =
>             min_recovery > cook_item.life_recover ? min_recovery : cook_item.life_recover;
> ```

sead::Mathf::max or clampMin?
___
*[`src/Game/Cooking/cookManager.cpp` line 148 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhiQZb7e2b9KLEYYoX:-NMhiQZb7e2b9KLEYYoY:bnpueue) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L148)):*
> ```cpp
>         for (int i = 0; i < NumIngredientsMax; i++) {
>             const auto& ingredient = ingredients[i];
>             if (ingredient.arg) {
> ```

Consider `if (!ingredient.arg) continue;` to reduce the level of indentation
___
*[`src/Game/Cooking/cookManager.cpp` line 182 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhilkq7skLO-GOaEYB:-NMhilkq7skLO-GOaEYC:b-wz8y51) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L182)):*
> ```cpp
>     switch (sead::GlobalRandom::instance()->getS32Range(effect_min, effect_max)) {
>     case 0:
>         cook_item.life_recover += (f32)mCookingEffectEntries[(int)CookEffectId::LifeRecover].ssa;
> ```

I think it would make sense to have a cooking effect entry getter so that the CookEffectId -> int cast can be abstracted away
___
*[`src/Game/Cooking/cookManager.cpp` line 307 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjDOR02T4ZLndYO04:-NMhjDOR02T4ZLndYO05:b-skfgnv) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L307)):*
> ```cpp
> 
>         if (InfoData::instance()->hasTag(ingredients[i].actor_data, tags::CookEnemy) ||
>             !InfoData::instance()->hasTag(ingredients[i].actor_data, tags::CookSpice))
> ```

braces
___
*[`src/Game/Cooking/cookManager.cpp` line 322 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjQ8p6w2XBTdrpTub:-NMhjQ8p6w2XBTdrpTuc:b-sw7wys) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L322)):*
> ```cpp
>         if (ingredients[i].actor_data.tryGetIntByKey(&int_val, "cookSpiceBoostMaxHeartLevel") &&
>             int_val > 0) {
>             // i < 1 check needs to come after others.
> ```

iirc we matched this by using a (bugged) loop?
```cpp
for (int j = 0; i < 1; ++i) {
...
}
```
___
*[`src/Game/Cooking/cookManager.cpp` line 390 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjo1EE6OTJFJoS9xI:-NMhjo1EE6OTJFJoS9xJ:b-cceucd) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L390)):*
> ```cpp
> 
>     if (mult_idx >= 1) {
>         price = (s32)(mIngredientNumMultipliers[mult_idx - 1] * (float)cook_item.item_price);
> ```

The `price` variable probably doesn't exist
___
*[`src/Game/Cooking/cookManager.cpp` line 575 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkHOp6KAo14xUp4hM:-NMhkHOp6KAo14xUp4hN:be8pc9u) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L575)):*
> ```cpp
>     CookEffectId entry_idx;
> 
>     if (sCrc32Constants.crc32_life_recover == name_hash)
> ```

Does this match as a switch statement (switching on `name_hash`)?
___
*[`src/Game/Cooking/cookManager.cpp` line 645 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkUMJ8ZoIQGEwYeq6:-NMhkUMJ8ZoIQGEwYeq7:b-6qzavg) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L645)):*
> ```cpp
>     }
> 
>     mIngredientNumMultipliers[0] = 1.0f;
> ```

Does this match? `mIngredientNumMultipliers.fill(1.0f);`
___
*[`src/Game/Cooking/cookManager.cpp` line 651 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkXC-99SXNjlhbRpq:-NMhkXC-99SXNjlhbRpr:blt4ldf) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L651)):*
> ```cpp
>     mIngredientNumMultipliers[4] = 1.0f;
> 
>     mIngredientNumSuccessRates[0] = 0;
> ```

Does this match?
```cpp
for (int i = 0; i < n; ++i)
  mIngredientNumSuccessRates[i] = 5 * i;
```
___
*[`src/Game/Cooking/cookManager.cpp` line 1091 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhlDfz5sbig-AjBQVS:-NMhlDfz5sbig-AjBQVT:b-ppxtt9) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L1091)):*
> ```cpp
>                                   int num_ingredients, CookItem& cook_item) const {
>     for (int i = 0; i < NumIngredientsMax; i++) {
>         arg.ingredients[i].name = "";
> ```

Does `arg.ingredients[i] = {};` match?

**Review by TheGreatB3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/113)* status: 11 of 16 files reviewed, 17 unresolved discussions (waiting on @leoetlino)

___
*[`src/Game/AI/Action/actionSetCookItemInDemo.cpp` line 18 at r1](https://reviewable.io/reviews/zeldaret/botw/113#-NMclFrY0LnNH2fBzvjc:-NMijhwL0pOInFZ-erpb:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/56deac33b8686c7ab621cb82ec56e4054d3dbf8d/src/Game/AI/Action/actionSetCookItemInDemo.cpp#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

IMO it would be preferable to set the two members to false by default (by adding default member initialisers) so we can avoid having to silence the lint warning manually
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiCookPotRoot.cpp` line 59 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhfjhFDSgf4TjhBzEK:-NMilfIqBRMn7ayRp3vs:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/AI/AI/aiCookPotRoot.cpp#L59)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

auto*
</blockquote></details>

Done.
___
*[`src/Game/AI/AI/aiCookPotRoot.cpp` line 63 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhfo9g4Vzh9cfmfF4p:-NMilfXZD_IAn1Zq9peo:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/AI/AI/aiCookPotRoot.cpp#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Consider using designated initialisers here (even though they are not standard prior to C++20, they improve readability a lot)
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.h` line 9 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhgq-n1vTxy2Y3NmyL:-NMimbgN6cmRrRH1qc2N:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.h#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`#include <...>`
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.h` line 79 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhgLHZ-mkO2cy_eqGe:-NMin1gr6sr0mOPxx8QH:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.h#L79)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think the [[maybe_unused]] attribute should probably only be in the .cpp
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 82 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhAEoC_gtjahaJMAo:-NMio6nB0CBqFPiAB2Na:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L82)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`util::safeDelete(mConfig);`
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 96 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhqoY88pTwosOOuh3:-NMjTcZM24WLBym16hTF:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L96)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Those casts are a bit ugly – consider hiding them behind a getter function (especially as cookFailForMissingConfig has the same casts)
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 98 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhhYo_3dfBTJbn_caC:-NMippj-9Y4QC1sXK6YU:b-erznae) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L98)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

sead::Mathf::max or clampMin?
</blockquote></details>

Done. Those cause the operand order to be wrong..
___
*[`src/Game/Cooking/cookManager.cpp` line 148 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhiQZb7e2b9KLEYYoX:-NMiqtn3DI9HL1JPBGTz:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L148)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Consider `if (!ingredient.arg) continue;` to reduce the level of indentation
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 182 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhilkq7skLO-GOaEYB:-NMivfZvEZIDNsyCIlaD:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L182)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think it would make sense to have a cooking effect entry getter so that the CookEffectId -> int cast can be abstracted away
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 307 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjDOR02T4ZLndYO04:-NMixePa8O58nWM_I3iG:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L307)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 322 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjQ8p6w2XBTdrpTub:-NMixekn42UhpQ7Elxs5:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L322)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

iirc we matched this by using a (bugged) loop?
```cpp
for (int j = 0; i < 1; ++i) {
...
}
```
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 390 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhjo1EE6OTJFJoS9xI:-NMjfwu76rnTKfZFBLnv:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L390)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

The `price` variable probably doesn't exist
</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 575 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkHOp6KAo14xUp4hM:-NMj5o06AlaLFrNS4Cpz:b-lra91b) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L575)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match as a switch statement (switching on `name_hash`)?
</blockquote></details>

Done. Those hashes aren't compile-time constants, so a switch can't be used here.
___
*[`src/Game/Cooking/cookManager.cpp` line 645 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkUMJ8ZoIQGEwYeq6:-NMj4NVFDDwiCtcULohZ:b-6t3ih4) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L645)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match? `mIngredientNumMultipliers.fill(1.0f);`
</blockquote></details>

Done. It doesn't, but a for loop does. 
___
*[`src/Game/Cooking/cookManager.cpp` line 651 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkXC-99SXNjlhbRpq:-NMj4WMxBktTXpdUxPMN:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L651)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match?
```cpp
for (int i = 0; i < n; ++i)
  mIngredientNumSuccessRates[i] = 5 * i;
```

</blockquote></details>

Done.
___
*[`src/Game/Cooking/cookManager.cpp` line 1091 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhlDfz5sbig-AjBQVS:-NMj5Vak1vxpmnPQGw60:b-ovavrw) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L1091)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does `arg.ingredients[i] = {};` match?
</blockquote></details>

Done. Does not match.

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/113)* status: all files reviewed, 1 unresolved discussion (waiting on @TheGreatB3)

___
*[`src/Game/Cooking/cookManager.cpp` line 575 at r2](https://reviewable.io/reviews/zeldaret/botw/113#-NMhkHOp6KAo14xUp4hM:-NMkXwKg-gvu4BQYkyHE:brheif5) ([raw file](https://github.com/zeldaret/botw/blob/c1cce7dd1f962debac009090b81191d79b1513c8/src/Game/Cooking/cookManager.cpp#L575)):*
<details><summary><i>Previously, TheGreatB3 (Briggs Baltzell) wrote…</i></summary><blockquote>

Done. Those hashes aren't compile-time constants, so a switch can't be used here.
</blockquote></details>

Oh right, the hashes are only const, not constexpr. Never mind.
___
*[`src/Game/Cooking/cookManager.cpp` line 396 at r3](https://reviewable.io/reviews/zeldaret/botw/113#-NMkXp2x9I3Pooi4RNd-:-NMkXp2y4Ye_2n0YMuZ9:b-sj1yek) ([raw file](https://github.com/zeldaret/botw/blob/e20b8cfd2d85888faba3c786f51e364a9d542d05/src/Game/Cooking/cookManager.cpp#L396)):*
> ```cpp
>     }
> 
>     // clamp, clampMin, and max don't work here.
> ```

```cpp
    cook_item.item_price = sead::Mathi::min(max_price, cook_item.item_price);
    cook_item.item_price = sead::Mathi::max(cook_item.item_price, 2);
```
^ this seems to also match

**Review by TheGreatB3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/113)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[`src/Game/Cooking/cookManager.cpp` line 396 at r3](https://reviewable.io/reviews/zeldaret/botw/113#-NMkXp2x9I3Pooi4RNd-:-NMo2mbP8yLsi0pWDHD-:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/e20b8cfd2d85888faba3c786f51e364a9d542d05/src/Game/Cooking/cookManager.cpp#L396)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

```cpp
    cook_item.item_price = sead::Mathi::min(max_price, cook_item.item_price);
    cook_item.item_price = sead::Mathi::max(cook_item.item_price, 2);
```
^ this seems to also match
</blockquote></details>

Done.

**Pull request merged**
