### PR TITLE
ksys: Add SystemTimers

### PR DESCRIPTION
**Pull request by MonsterDruide1**
All functions match perfectly. The member variable names could be improved to better reflect their functionality, but I don't know enough about their usage to properly describe them in their names.

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/57)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/57)* status: all files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQTrzY9DFzxHGsLViv:-MgQTrzY9DFzxHGsLViw:b-7tobje) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L9)):*
> ```objc
> namespace ksys::map {
> 
> class __attribute__((aligned(8))) PlacementGlobal {
> ```

The attribute should be removed.
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQTyFw5cGo1Y1bRT9G:-MgQTyFw5cGo1Y1bRT9H:b7i6m65) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L14)):*
> ```objc
>     PlacementGlobal() = default;
>     virtual ~PlacementGlobal();
>     void init();
> ```

`public:` between the dtor and this line
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 15 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQU0W_CyqAeeP-oUK2:-MgQU0W_CyqAeeP-oUK3:bkd1jua) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L15)):*
> ```objc
>     virtual ~PlacementGlobal();
>     void init();
>     void __auto();
> ```

This should be renamed (init2?). Do not use names containing double underscores `__` in C++; they're reserved for the implementation. And in general, do not use automatically generated or placeholder names.
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQUHBYEoGbPF_SlqU3:-MgQUHBYEoGbPF_SlqU4:b-r3oxk5) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L20)):*
> ```objc
>     void incrementCounters();
> 
>     unsigned int frameCounter = 0;
> ```

naming convention?
___
*[src/KingSystem/Map/mapPlacementGlobal.cpp, line 23 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQUNI34oFSKrmXpd0n:-MgQUNI34oFSKrmXpd0o:bje9lno) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.cpp#L23)):*
> ```cpp
> 
> void PlacementGlobal::__auto() {
>     vfrTimer = 0;
> ```

you might be able to get away with just calling `init()` here (since init will get inlined)

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/57)* status: all files reviewed, 5 unresolved discussions (waiting on @leoetlino)

___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 9 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQTrzY9DFzxHGsLViv:-MgQYIBeBve0vZdrPi1J:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

The attribute should be removed.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 14 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQTyFw5cGo1Y1bRT9G:-MgQYNGo7c7GDTB7ra3m:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L14)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`public:` between the dtor and this line
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 15 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQU0W_CyqAeeP-oUK2:-MgQYSIm07UiTenLxy4Z:b2afka3) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L15)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be renamed (init2?). Do not use names containing double underscores `__` in C++; they're reserved for the implementation. And in general, do not use automatically generated or placeholder names.
</blockquote></details>

Done. Actually, the now called `init` was called `init2` in the IDA database and `__auto` was named `__auto0`... so maybe they even should be called the other way around?
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQUHBYEoGbPF_SlqU3:-MgQZ1y04WcVHu5sNak7:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L20)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

naming convention?
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementGlobal.cpp, line 23 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQUNI34oFSKrmXpd0n:-MgQZ-gO4zHhz3DjpJRI:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.cpp#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

you might be able to get away with just calling `init()` here (since init will get inlined)
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/57)* status: all files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/KingSystem/System/SystemTimers.cpp, line 3 at r3](https://reviewable.io/reviews/zeldaret/botw/57#-MgQ_TyrEFsKlpf2IPw2:-MgQ_TyrEFsKlpf2IPw3:b-450u1h) ([raw file](https://github.com/zeldaret/botw/blob/26b23e4ecbd9d024b29d60d3a6fab8c8731e9174/src/KingSystem/System/SystemTimers.cpp#L3)):*
> ```cpp
> #include "KingSystem/System/SystemTimers.h"
> 
> #include <mc/seadCoreInfo.h>
> ```

These two includes can be removed (since the TLS stuff turned out to be an inlined VFR::getDeltaTime() call).
___
*[src/KingSystem/System/SystemTimers.cpp, line 9 at r3](https://reviewable.io/reviews/zeldaret/botw/57#-MgQ__mc-3dHC8WXKG1w:-MgQ__mc-3dHC8WXKG1x:b5ia4p5) ([raw file](https://github.com/zeldaret/botw/blob/26b23e4ecbd9d024b29d60d3a6fab8c8731e9174/src/KingSystem/System/SystemTimers.cpp#L9)):*
> ```cpp
> namespace ksys {
> 
> SEAD_SINGLETON_DISPOSER_IMPL(SystemTimers);
> ```

no need for the trailing semicolon (because what this macro does is define several functions)
___
*[src/KingSystem/Map/mapPlacementGlobal.h, line 15 at r1](https://reviewable.io/reviews/zeldaret/botw/57#-MgQU0W_CyqAeeP-oUK2:-MgQ_qRZ5uVd99s-ssk_:bewrnn) ([raw file](https://github.com/zeldaret/botw/blob/1aed13224676fb3245e6dbdf0aef543c9c4d4e8d/src/KingSystem/Map/mapPlacementGlobal.h#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Done. Actually, the now called `init` was called `init2` in the IDA database and `__auto` was named `__auto0`... so maybe they even should be called the other way around?
</blockquote></details>

I think the current names you chose are fine. Don't follow the IDA database too closely, sometimes I don't think too much about names :)

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Pull request merged**
