### PR TITLE
Implement ksys::phys::CharacterPrismShape class

### PR DESCRIPTION
**Pull request by TheGreatB3**
- Implemented `CharacterPrismShape`
- Also added `hkcdVertex` implementation

- - -
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/106)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
mostly LGTM, just a few minor comments

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/106#-:-NHKZ9865bm0bzmOok47:b47gqhz)* status: all files reviewed, 4 unresolved discussions (waiting on @TheGreatB3)

___
*[`src/KingSystem/Physics/physMaterialMask.h` line 44 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKX29vC44SgxdyQqwM:-NHKX29vC44SgxdyQqwN:undefined) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/physMaterialMask.h#L44)):*
> ```objc
>     }
> 
>     bool getCustomFlag(CustomFlag custom_flag) {
> ```





_Suggestion:_
```objc
bool getCustomFlag(CustomFlag custom_flag) const {
```
___
*[`src/KingSystem/Physics/RigidBody/Shape/physShapeParamObj.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKXChf9cSNWtZGMi7d:-NHKXChf9cSNWtZGMi7e:b-rzf91) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/physShapeParamObj.cpp#L16)):*
> ```cpp
>       convex_radius(0.05, "convex_radius", this),
>       translate_0(sead::Vector3f::zero, "translate_0", this),
>       translate_1(sead::Vector3f::zero, "offset", this),
> ```

You sure about this change? (is this a find & replace gone wrong?)
___
*[`src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp` line 22 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKYFq58Q0450N9ttCS:-NHKYFq58Q0450N9ttCT:bhzdzqm) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp#L22)):*
> ```cpp
> CharacterPrismShape* CharacterPrismShape::make(const CharacterPrismShapeParam& param,
>                                                sead::Heap* heap) {
>     PolytopeShapeParam polytopeShapeParam;
> ```

We use `lowercase_snake_case` for variable names (that aren't class member variables or static variables). See https://botw.link/contribute/coding-guidelines#naming
___
*[`src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp` line 24 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKXmKy272vCrvIqZNc:-NHKXmKy272vCrvIqZNd:bn1n0u5) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp#L24)):*
> ```cpp
>     PolytopeShapeParam polytopeShapeParam;
>     polytopeShapeParam.vertex_num = SHAPE_VERTEX_NUM;
>     polytopeShapeParam.common.material = param.common.material;
> ```

Does this match? `polytopeShapeParam.common = param.common;`

**Review by TheGreatB3 — COMMENTED** [review]
Made requested fixes.

> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/106#-:-NHLHfsz3Qd4MKEErm5V:b-incf31)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/Physics/physMaterialMask.h` line 44 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKX29vC44SgxdyQqwM:-NHLHBZz8-TKPDibhUAU:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/physMaterialMask.h#L44)):*
> ```objc
>     }
> 
>     bool getCustomFlag(CustomFlag custom_flag) {
> ```

Done.
___
*[`src/KingSystem/Physics/RigidBody/Shape/physShapeParamObj.cpp` line 16 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKXChf9cSNWtZGMi7d:-NHLH4g00ryDguK_ngAw:b-c6k8d1) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/physShapeParamObj.cpp#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

You sure about this change? (is this a find & replace gone wrong?)
</blockquote></details>

Fixed. It was a bad rename.
___
*[`src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp` line 22 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKYFq58Q0450N9ttCS:-NHLH2rR8HxnYBYJtaJJ:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp#L22)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

We use `lowercase_snake_case` for variable names (that aren't class member variables or static variables). See https://botw.link/contribute/coding-guidelines#naming
</blockquote></details>

Done.
___
*[`src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp` line 24 at r1](https://reviewable.io/reviews/zeldaret/botw/106#-NHKXmKy272vCrvIqZNc:-NHLGaJX9hHqmMmhTamE:big5828) ([raw file](https://github.com/zeldaret/botw/blob/b6a15be7bcaa46f4e8265c1a38ae8ddbf10324c9/src/KingSystem/Physics/RigidBody/Shape/CharacterPrism/physCharacterPrismShape.cpp#L24)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match? `polytopeShapeParam.common = param.common;`
</blockquote></details>

Unfortunately that doesn't match. I'm not sure why.

**Review by leoetlino — APPROVED** [review]
LGTM other than the lint issue

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/106#-:-NHL_iXo-CHDg59Pjy1A:bls2xpv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TheGreatB3)

**Review by TheGreatB3 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/106#-:-NHLjsdXEIDK1Cz2BAv5:b-896fix)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @leoetlino)

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TheGreatB3)

**Pull request merged**
