### PR TITLE
Add initial PlacementMap functions

### PR DESCRIPTION
**Pull request by savage13**
Added some initial functions to PlacementMap

There are some changes to associated classes:
- PlacementActors
- StaticCompound

---
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)* status: all files reviewed, 9 unresolved discussions (waiting on @savage13)

___
*[src/KingSystem/Map/mapPlacementActors.h, line 120 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWCLlJ0tlWeaYpOhIp:-MuWCLlJ0tlWeaYpOhIq:b-7n96zx) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementActors.h#L120)):*
> ```objc
> 
>     u8 _0[0x28 - 0x0];
>     sead::ReadWriteLock lock;
> ```

mLock
___
*[src/KingSystem/Map/mapPlacementMap.h, line 96 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEQ1T48Vmfn-4HAaX:-MuWEQ1T48Vmfn-4HAaY:b4f33qv) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.h#L96)):*
> ```objc
>     void x_9();
> 
>     void x_7(int idx, int unknown, s8 column, s8 row, const sead::SafeString& mubinPath,
> ```

`mubin_path`, `folder_and_file`
___
*[src/KingSystem/Map/mapPlacementMap.h, line 101 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDTZ4Bn1BKBA6t4rN:-MuWDTZ4Bn1BKBA6t4rO:bh8mkiz) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.h#L101)):*
> ```objc
>     u8 _0;
>     u8 mSkipLoadStaticMap;
>     u8 mStaticMapLoaded[2];
> ```

`bool mStaticMapLoaded; bool mStaticMapParsed;`? And StaticMap can probably be removed now.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 53 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDhI33WaHPbUJES68:-MuWDhI33WaHPbUJES69:b-zhmaqr) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L53)):*
> ```cpp
> 
> phys::BodyGroup* PlacementMap::getFieldBodyGroup(u32 field_group) {
>     mCs.lock();
> ```

Does this match if you use a sead::ScopedLock? (construct a scoped lock guard with sead::makeScopedLock)

If so, consider returning the values directly instead of using a variable for the return value.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 57 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEpr87xYzB011ZMAI:-MuWEpr87xYzB011ZMAJ:boetxpd) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L57)):*
> ```cpp
>     auto* r = mRes[0].mRes.getResource();
>     if (auto* sc = sead::DynamicCast<phys::StaticCompound>(r)) {
>         if (sc->fieldBodyGroupSize() > (s32)field_group) {
> ```

`field_group` should probably be an s32/int in the first place. Also consider renaming field_group to field_group_idx otherwise it's not immediately clear what the argument is.

One last thing: `if (field_group_idx < sc->fieldBodyGroupSize())` would be a more natural way to check the index.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 71 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDzX56fMiD05R7YqY:-MuWDzX56fMiD05R7YqZ:brrw5p7) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L71)):*
> ```cpp
>                        const sead::SafeString& folderAndFile, int map_id_maybe,
>                        bool skip_load_static_map) {
>     _388 = unknown;  // Unknown
> ```

I'm not sure the comment is necessary. The variable is already called unknown.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 77 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWE9Ip3jFqdplowg7R:-MuWE9Ip3jFqdplowg7S:b-urq0ph) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L77)):*
> ```cpp
>     mMubinPath.copy(mubinPath);
>     mFolderAndFile.copy(folderAndFile);
>     _38c = map_id_maybe; /* Index in open world map */
> ```

C++ style comments please (`//` instead of `/* */`)
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 82 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEZRrErD3UVxvP8nc:-MuWEZRrErD3UVxvP8nd:bpqf5ha) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L82)):*
> ```cpp
> 
> void PlacementMap::unloadHksc(s32 a2) {
>     u64 k = ((u64)a2 < 4) ? a2 : 0;
> ```

This can almost surely be removed. SafeArray's operator[] already performs this kind of bounds checking for you.
___
*[src/KingSystem/Physics/StaticCompound/physStaticCompound.h, line 46 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWF9jMDytaPq9oAizw:-MuWF9jMDytaPq9oAizx:b-pz1rti) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Physics/StaticCompound/physStaticCompound.h#L46)):*
> ```objc
>     void cleanUp();
>     bool calledFromMapDtor();
>     inline s32 fieldBodyGroupSize() { return mFieldBodyGroups.size(); }
> ```

`int getNumFieldBodyGroups() const` (no need for inline, int rather than s32 for consistency, const-qualify the member function since it doesn't modify object state)

**Review by savage13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)* status: all files reviewed, 9 unresolved discussions (waiting on @leoetlino)

___
*[src/KingSystem/Map/mapPlacementActors.h, line 120 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWCLlJ0tlWeaYpOhIp:-Mu_i4_w78dtyyvp3rpP:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementActors.h#L120)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

mLock
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 96 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEQ1T48Vmfn-4HAaX:-Mu_iG1L3MtKPn1e5RED:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.h#L96)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`mubin_path`, `folder_and_file`
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.h, line 101 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDTZ4Bn1BKBA6t4rN:-Mu_j62bDxOp0hfPR3q3:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.h#L101)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`bool mStaticMapLoaded; bool mStaticMapParsed;`? And StaticMap can probably be removed now.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 53 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDhI33WaHPbUJES68:-Mu_lSu-0rTa5MFdzMU8:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Does this match if you use a sead::ScopedLock? (construct a scoped lock guard with sead::makeScopedLock)

If so, consider returning the values directly instead of using a variable for the return value.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 57 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEpr87xYzB011ZMAI:-Mu_ku3H-q8t5dKJbBG_:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L57)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`field_group` should probably be an s32/int in the first place. Also consider renaming field_group to field_group_idx otherwise it's not immediately clear what the argument is.

One last thing: `if (field_group_idx < sc->fieldBodyGroupSize())` would be a more natural way to check the index.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 71 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWDzX56fMiD05R7YqY:-Mu_jGFR2GltpdltdsFu:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L71)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I'm not sure the comment is necessary. The variable is already called unknown.
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 77 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWE9Ip3jFqdplowg7R:-Mu_jGvj1d84QIXKhksd:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L77)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

C++ style comments please (`//` instead of `/* */`)
</blockquote></details>

Done.
___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 82 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWEZRrErD3UVxvP8nc:-Mu_jf6dA00tp55LS2lW:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Map/mapPlacementMap.cpp#L82)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This can almost surely be removed. SafeArray's operator[] already performs this kind of bounds checking for you.
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/StaticCompound/physStaticCompound.h, line 46 at r1](https://reviewable.io/reviews/zeldaret/botw/79#-MuWF9jMDytaPq9oAizw:-Mu_jqEoD2fpfp5luPcE:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/432cfd96682f7150d13887b58e11fd5955b6d9f2/src/KingSystem/Physics/StaticCompound/physStaticCompound.h#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`int getNumFieldBodyGroups() const` (no need for inline, int rather than s32 for consistency, const-qualify the member function since it doesn't modify object state)
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)* status: all files reviewed, 2 unresolved discussions (waiting on @savage13)

___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 53 at r2](https://reviewable.io/reviews/zeldaret/botw/79#-Mu_nsGK9AXVx64vPyoU:-Mu_nsGK9AXVx64vPyoV:b-64qs2u) ([raw file](https://github.com/zeldaret/botw/blob/c67a0f3b3714b3b90985039a419d19c2b797b8da/src/KingSystem/Map/mapPlacementMap.cpp#L53)):*
> ```cpp
> 
> phys::BodyGroup* PlacementMap::getFieldBodyGroup(int field_group_idx) {
>     const auto lock = sead::makeScopedLock(mCs);
> ```

don't forget to include `<prim/seadScopedLock.h>`
___
*[src/KingSystem/Physics/StaticCompound/physStaticCompound.h, line 46 at r2](https://reviewable.io/reviews/zeldaret/botw/79#-Mu_o6yoDC_BUPghnEcb:-Mu_o6yoDC_BUPghnEcc:b-decj2h) ([raw file](https://github.com/zeldaret/botw/blob/c67a0f3b3714b3b90985039a419d19c2b797b8da/src/KingSystem/Physics/StaticCompound/physStaticCompound.h#L46)):*
> ```objc
>     void cleanUp();
>     bool calledFromMapDtor();
>     int fieldBodyGroupSize() const { return mFieldBodyGroups.size(); }
> ```

"size" might be a bit ambiguous: it could mean the size of the "field body group" (the number of elements in one unspecified group). Just replacing "size" with "number" has the same problem: "fieldBodyGroupNumber" could mean the number of groups OR the number of an unspecified group.

I think getNumberOfFieldBodyGroups (or getNumFieldBodyGroups to shorten it) would work better.

**Review by savage13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[src/KingSystem/Map/mapPlacementMap.cpp, line 53 at r2](https://reviewable.io/reviews/zeldaret/botw/79#-Mu_nsGK9AXVx64vPyoU:-Mu_qHJgD6My-urYxT2n:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c67a0f3b3714b3b90985039a419d19c2b797b8da/src/KingSystem/Map/mapPlacementMap.cpp#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

don't forget to include `<prim/seadScopedLock.h>`
</blockquote></details>

Done.
___
*[src/KingSystem/Physics/StaticCompound/physStaticCompound.h, line 46 at r2](https://reviewable.io/reviews/zeldaret/botw/79#-Mu_o6yoDC_BUPghnEcb:-Mu_qJRABchJB0A0pSvp:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/c67a0f3b3714b3b90985039a419d19c2b797b8da/src/KingSystem/Physics/StaticCompound/physStaticCompound.h#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

"size" might be a bit ambiguous: it could mean the size of the "field body group" (the number of elements in one unspecified group). Just replacing "size" with "number" has the same problem: "fieldBodyGroupNumber" could mean the number of groups OR the number of an unspecified group.

I think getNumberOfFieldBodyGroups (or getNumFieldBodyGroups to shorten it) would work better.
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79#-:-Mu_rVOP17kIac8-nkqj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @savage13)

**Comment by leoetlino** [comment]
Please squash code review fixes into the first commit:

* `git remote add upstream https://github.com/zeldaret/botw`
* `git fetch upstream`
* `git rebase -i upstream/master` (this is called an *interactive rebase*)
* you'll see something like this appear in your text editor:

```
pick 4701d009 first commit message
pick a35750df second commit message
pick xxxxxxxx third
```

* for every commit you want to merge with the previous commit (on the previous line), change `pick` into `fixup` (or `f`)
  * you can reorder commits if necessary 
  * it is also possible to change commit messages during an interactive rebase: use `r` to **r**eword a commit message
* save and close the editor
* `git push --force`

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @savage13)

**Pull request merged**
