### PR TITLE
mapRail.cpp ok

### PR DESCRIPTION
**Pull request by notyourav**
This change is [Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)

### CODE REVIEW

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)* status: 4 of 5 files reviewed, 21 unresolved discussions (waiting on @notyourav)

___
*[`src/KingSystem/Map/mapRail.h` line 19 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_0gF0VWKvFJiZpY2:-NW4_0gF0VWKvFJiZpY3:b-o4ydg5) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L19)):*
> ```objc
>     virtual bool parse(MubinIter* iter, sead::Heap* heap);
> 
>     const MubinIter* getIter() const;
> ```

this should probably return a reference instead as it's never null
___
*[`src/KingSystem/Map/mapRail.h` line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_8m35YKDJXcC1sov:-NW4_8m35YKDJXcC1sow:b2nibfy) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L20)):*
> ```objc
> 
>     const MubinIter* getIter() const;
>     const sead::Vector3f* getRotate() const;
> ```

ref
___
*[`src/KingSystem/Map/mapRail.h` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_98eD26WHPwj31sN:-NW4_98eD26WHPwj31sO:b2nibfy) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L21)):*
> ```objc
>     const MubinIter* getIter() const;
>     const sead::Vector3f* getRotate() const;
>     const sead::Vector3f* getTranslate() const;
> ```

ref
___
*[`src/KingSystem/Map/mapRail.h` line 26 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_MAjE_cUwCo8gNAi:-NW4_MAjE_cUwCo8gNAj:bb7k8ul) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L26)):*
> ```objc
> 
> protected:
>     SRT srt;
> ```

mSrt
___
*[`src/KingSystem/Map/mapRail.h` line 27 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_Ny18m7H5RNAAV5G:-NW4_Ny18m7H5RNAAV5H:b-wcsy40) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L27)):*
> ```objc
> protected:
>     SRT srt;
>     ControlPoints ctrl_points;
> ```

mCtrlPoints and so on
___
*[`src/KingSystem/Map/mapRail.h` line 33 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4aDxHB8OAlCrAaRDZ:-NW4aDxHB8OAlCrAaRD_:b-2h0uvt) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L33)):*
> ```objc
> };
> 
> class RailBase {
> ```

I wonder if it makes sense to just call this Rail - RailBase is a bit awkward imo
___
*[`src/KingSystem/Map/mapRail.h` line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_S6g340vnIpfOJGw:-NW4_S6g340vnIpfOJGx:b-e40bxl) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L40)):*
> ```objc
>     virtual s32 x_18() { return 0; }
>     virtual s32 x_20() { return 0; }
>     virtual RailPoint* allocRail(sead::Heap* heap);
> ```

allocRail or allocRailPoint?
___
*[`src/KingSystem/Map/mapRail.h` line 44 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_aox4ZuOszdu6Gvs:-NW4_aox4ZuOszdu6Gvt:bembyy) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L44)):*
> ```objc
>     virtual void x_38() {}
> 
>     s32 getSize() const;
> ```

getNumPoints would be less ambiguous imo
___
*[`src/KingSystem/Map/mapRail.h` line 45 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_cjq9dPeW6fSlcNV:-NW4_cjq9dPeW6fSlcNW:b-c7jugs) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L45)):*
> ```objc
> 
>     s32 getSize() const;
>     RailPoint* getPoint(s32 idx) const;
> ```

presumably one of these is returning RailPoint& and the other one is a const member function that returns const RailPoint&
___
*[`src/KingSystem/Map/mapRail.h` line 47 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_l6_CbFK2YzJNz7z:-NW4_l6_CbFK2YzJNz8-:buregg5) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L47)):*
> ```objc
>     RailPoint* getPoint(s32 idx) const;
>     RailPoint* getPoint_0(s32 idx) const;
>     SRT* getPointSRT(s32 idx) const;
> ```

these should all return references (or maybe const references)
___
*[`src/KingSystem/Map/mapRail.h` line 61 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_v_D9sWBg2qYzQnO:-NW4_v_D9sWBg2qYzQnP:b-ftqj4s) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L61)):*
> ```objc
>     const char* getUniqueName() const;
> 
>     enum Flag : u32 {
> ```

`enum class` (otherwise this leaks the enum members into the surrounding name scope)
___
*[`src/KingSystem/Map/mapRail.cpp` line 66 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4a_FB3MfjlXTJPKnb:-NW4a_FB3MfjlXTJPKnc:bs3muq1) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L66)):*
> ```cpp
>             MubinIter node_iter;
>             if (result.tryGetIterByIndex(&node_iter, i)) {
>                 auto* n = [&] {
> ```

seems like this should be a separate member function? allocAndGetPoint (taking a heap and an index) maybe?
___
*[`src/KingSystem/Map/mapRail.cpp` line 139 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4aoOPEXJU4mzQ_UJi:-NW4aoOPEXJU4mzQ_UJj:bkxqytr) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L139)):*
> ```cpp
>     RailPoint* rail = new (heap) RailPoint;
> 
>     rail->srt.scale = sead::Vector3f::ones;
> ```

these are probably part of the RailPoint constructor? think this should just be `return (heap) RailPoint;` (after moving the initialisers into RailPoint)
___
*[`src/KingSystem/Map/mapRail.cpp` line 151 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bKg_2xEyhv29nLcs:-NW4bKg_2xEyhv29nLct:b180k0h) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L151)):*
> ```cpp
> }
> 
> bool RailBase::parse(MubinIter* iter) {
> ```

see discussion on Discord
___
*[`src/KingSystem/Map/mapRail.cpp` line 232 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bU0FED_hUv9R15NF:-NW4bU0FED_hUv9R15NG:blrmkcl) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L232)):*
> ```cpp
>     auto* rail = new (heap) RailRemainGuidePoint;
> 
>     rail->srt.scale = sead::Vector3f::ones;
> ```

yeah it definitely seems like this initialisation logic happens in RailPoint - seeing as it's inherited by RailRemainGuidePoint
___
*[`src/KingSystem/Map/mapRail.cpp` line 247 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bcLr6djrGPMg9eBt:-NW4bcLr6djrGPMg9eBu:bp3oj30) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L247)):*
> ```cpp
> 
> RailConnectablePoint::~RailConnectablePoint() {
>     sead::HeapMgr::instance()->getCurrentHeap();
> ```

lol this looks pretty fishy - I wonder if this is a leftover piece of debugging code?
___
*[`src/KingSystem/Map/mapRail.cpp` line 248 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bnes17s1WPCrEoub:-NW4bnes17s1WPCrEouc:b-v4kbpn) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L248)):*
> ```cpp
> RailConnectablePoint::~RailConnectablePoint() {
>     sead::HeapMgr::instance()->getCurrentHeap();
>     delete[] mJunctionPoint;
> ```

the reason this doesn't match is that you need to set mJunctionPoint to nullptr after deleting it. you can try `if (mJunctionPoint) util::safeDeleteArray(mJunctionPoint);`
___
*[`src/KingSystem/Map/mapRail.cpp` line 252 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4c6mZA4awPLJYGJiM:-NW4c6mZA4awPLJYGJiN:b-1v2o2r) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L252)):*
> ```cpp
> 
> RailBase* RailConnectablePoint::getJunctionRail() const {
>     return mJunctionRail;
> ```

where is mJunctionRail allocated?
___
*[`src/KingSystem/Map/mapRail.cpp` line 264 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cCdZ3_0ZVCK1rco3:-NW4cCdZ3_0ZVCK1rco4:br096en) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L264)):*
> ```cpp
> 
>     bool success = true;
>     if (!iter->tryGetFloatArrayByKey(srt.translate.e.data(), "Translate")) {
> ```

think the `success &=` you had in your first version is a nicer way of expressing this (hopefully it matches)
___
*[`src/KingSystem/Map/mapRail.cpp` line 351 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cLN3-SQcF9UDpC9U:-NW4cLN3-SQcF9UDpC9V:b-weog9z) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L351)):*
> ```cpp
>     bool result = false;
>     if (iter->tryGetParamBoolByKey(&result, "RenderEnabled")) {
>         if (result) {
> ```

does mFlags.change(...) match?
___
*[`src/KingSystem/Map/mapRail.cpp` line 386 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cOOoBFDxoRBTkFpO:-NW4cOOoBFDxoRBTkFpP:b-rbeps6) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L386)):*
> ```cpp
>     }
> 
>     return success & iter->tryGetParamStringByKey(&mRouteId, "RouteId");
> ```

`success &= ...; return success;`

**Comment by notyourav** [comment]
*[`src/KingSystem/Map/mapRail.h` line 45 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_cjq9dPeW6fSlcNV:-NW5vTJ2-yzY40ylvZBG:b-kze3q2) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L45)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

presumably one of these is returning RailPoint& and the other one is a const member function that returns const RailPoint&
</blockquote></details>

the getPoint functions have null checks so I am assuming they are pointers? changing the others tho

**Comment by notyourav** [comment]
*[`src/KingSystem/Map/mapRail.cpp` line 252 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4c6mZA4awPLJYGJiM:-NW6D0Jc8OAqwcihTXV-:brqt27g) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L252)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

where is mJunctionRail allocated?
</blockquote></details>

0x7100D5C3B0 here, I believe its an array of Rail pointers

**Comment by notyourav** [comment]
*[`src/KingSystem/Map/mapRail.cpp` line 351 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cLN3-SQcF9UDpC9U:-NW6DC3bBCPJuwjEcx2J:b-7m4ph4) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L351)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

does mFlags.change(...) match?
</blockquote></details>

no :(

**Review by notyourav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)* status: 1 of 5 files reviewed, 21 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/Map/mapRail.h` line 19 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_0gF0VWKvFJiZpY2:-NW6Hfsj7Q6ODjAg52lV:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this should probably return a reference instead as it's never null
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 20 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_8m35YKDJXcC1sov:-NW6HgRN7qA2TwMVUaRX:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L20)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ref
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 21 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_98eD26WHPwj31sN:-NW6Hgsj1IbE5OtJwWoc:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ref
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 26 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_MAjE_cUwCo8gNAi:-NW6HhIg-JQCqkaPpezb:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L26)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

mSrt
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 27 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_Ny18m7H5RNAAV5G:-NW6Hi86AwO5fSqQA60j:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

mCtrlPoints and so on
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 33 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4aDxHB8OAlCrAaRDZ:-NW6HiayE1U2vVmNI83_:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I wonder if it makes sense to just call this Rail - RailBase is a bit awkward imo
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 40 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_S6g340vnIpfOJGw:-NW6Hj-T-WxPM3EhC8QY:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L40)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

allocRail or allocRailPoint?
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 44 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_aox4ZuOszdu6Gvs:-NW6Hkwr1oMI69y00dau:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L44)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

getNumPoints would be less ambiguous imo
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 47 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_l6_CbFK2YzJNz7z:-NW6HmLOC5aPN_HnVWue:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L47)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

these should all return references (or maybe const references)
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.h` line 61 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_v_D9sWBg2qYzQnO:-NW6HnBv9tObsexo-nDb:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L61)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`enum class` (otherwise this leaks the enum members into the surrounding name scope)
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 66 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4a_FB3MfjlXTJPKnb:-NW6HohB2iZ_JY_4zRxM:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L66)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

seems like this should be a separate member function? allocAndGetPoint (taking a heap and an index) maybe?
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 139 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4aoOPEXJU4mzQ_UJi:-NW6KFCr3new0L7H-0m-:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L139)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

these are probably part of the RailPoint constructor? think this should just be `return (heap) RailPoint;` (after moving the initialisers into RailPoint)
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 151 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bKg_2xEyhv29nLcs:-NW6KFnY9jA7kno4dzIr:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L151)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

see discussion on Discord
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 232 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bU0FED_hUv9R15NF:-NW6KGXt6aCiMG1ctv9i:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L232)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

yeah it definitely seems like this initialisation logic happens in RailPoint - seeing as it's inherited by RailRemainGuidePoint
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 247 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bcLr6djrGPMg9eBt:-NW6KH3FAvdBiaX1rt-y:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L247)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

lol this looks pretty fishy - I wonder if this is a leftover piece of debugging code?
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 248 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4bnes17s1WPCrEoub:-NW6KHWf5yEgN5h3k9Cq:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L248)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the reason this doesn't match is that you need to set mJunctionPoint to nullptr after deleting it. you can try `if (mJunctionPoint) util::safeDeleteArray(mJunctionPoint);`
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 264 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cCdZ3_0ZVCK1rco3:-NW6KIPr1fcBXnj1JjQK:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L264)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

think the `success &=` you had in your first version is a nicer way of expressing this (hopefully it matches)
</blockquote></details>

Done.
___
*[`src/KingSystem/Map/mapRail.cpp` line 386 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cOOoBFDxoRBTkFpO:-NW6KJTr1PB28ZtvRmNx:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L386)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`success &= ...; return success;`
</blockquote></details>

Done.

**Review by leoetlino — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @notyourav)

___
*[`src/KingSystem/Map/mapRail.h` line 45 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4_cjq9dPeW6fSlcNV:-NW8jKmx6L1AZpUYhKlw:b-8mape) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.h#L45)):*
<details><summary><i>Previously, notyourav wrote…</i></summary><blockquote>

the getPoint functions have null checks so I am assuming they are pointers? changing the others tho
</blockquote></details>

ah fair enough, sorry I missed it was nullable
___
*[`src/KingSystem/Map/mapRail.h` line 55 at r2](https://reviewable.io/reviews/zeldaret/botw/118#-NW8jRA04pxN1thrKSpA:-NW8jRA04pxN1thrKSpB:b-2dmwpt) ([raw file](https://github.com/zeldaret/botw/blob/2ccf4f7fd2e2b58924484134ea0d0ed534d4e0b5/src/KingSystem/Map/mapRail.h#L55)):*
> ```objc
>     s32 getNumPoints() const;
>     const RailPoint* getPoint(s32 idx) const;
>     RailPoint* getPoint_0(s32 idx);
> ```

getPoint
___
*[`src/KingSystem/Map/mapRail.cpp` line 386 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cOOoBFDxoRBTkFpO:-NW8k7PZ6NksGvhGlHxF:bfi91ky) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L386)):*
<details><summary><i>Previously, notyourav wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done :P
___
*[`src/KingSystem/Map/mapRail.cpp` line 58 at r2](https://reviewable.io/reviews/zeldaret/botw/118#-NW8jZ3P0yrv-268AHaU:-NW8jZ3P0yrv-268AHaV:bq044t8) ([raw file](https://github.com/zeldaret/botw/blob/2ccf4f7fd2e2b58924484134ea0d0ed534d4e0b5/src/KingSystem/Map/mapRail.cpp#L58)):*
> ```cpp
>             MubinIter node_iter;
>             if (result.tryGetIterByIndex(&node_iter, i)) {
>                 RailPoint* n = allocPointIdx(i, heap);
> ```

nit: could we call this `point` or something more descriptive than `n` (which sounds like the name of an int variable)

**Review by leoetlino — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)* status: all files reviewed, 3 unresolved discussions (waiting on @notyourav)

**Review by notyourav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[`src/KingSystem/Map/mapRail.h` line 55 at r2](https://reviewable.io/reviews/zeldaret/botw/118#-NW8jRA04pxN1thrKSpA:-NWOV-ncDG-no7OORW-6:b-q5bshq) ([raw file](https://github.com/zeldaret/botw/blob/2ccf4f7fd2e2b58924484134ea0d0ed534d4e0b5/src/KingSystem/Map/mapRail.h#L55)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

getPoint
</blockquote></details>

Done 2 🥹
___
*[`src/KingSystem/Map/mapRail.cpp` line 386 at r1](https://reviewable.io/reviews/zeldaret/botw/118#-NW4cOOoBFDxoRBTkFpO:-NWOVRKW9JvRlyTHgBZR:b-896fix) ([raw file](https://github.com/zeldaret/botw/blob/ef8fe52a4385cc3d8026a3347ab8cac6c44b47d4/src/KingSystem/Map/mapRail.cpp#L386)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

not done :P
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
Looks great, thanks for working on this!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldaret/botw/118#-:-NWPQYDPBAMDZYQTUy9h:buo3n5b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @notyourav)

**Pull request merged**
